// scripts/og/render.mjs — regenerates the social share images.
//
//   node scripts/og/render.mjs
//
// Writes public/og-image-v3.png (default) and public/og-image-v3-alt.png
// (receipts + coupons copy), both 1200x630, from scripts/og/og.html.
//
// Built only from real brand assets:
//   - the PapeX lockup and plane mark: path data read straight out of
//     components/brand/full-logo.tsx and components/brand/plane-mark.tsx (the
//     site's single vector source), written to scripts/og/logo.generated.js so
//     og.html also opens correctly on its own in a browser;
//   - the local brand fonts in fonts/ (Kameron SemiBold, Barlow Medium);
//   - the brand palette (navy #00121D, orange #EB7100, blue #0088EA).
//
// No new dependencies: headless Chrome is driven over raw CDP (Node's built-in
// WebSocket, like .claude/tools/shoot.mjs), and the PNGs are recompressed with
// sharp, which the repo already uses for scripts/generate-brand-assets.mjs.
// Override the browser with CHROME=/path/to/chrome.

import { spawn } from 'node:child_process'
import { readFileSync, writeFileSync, rmSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
import sharp from 'sharp'

const HERE = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(HERE, '../..')
const W = 1200
const H = 630
const MAX_BYTES = 400 * 1024

const VARIANTS = [
  { key: 'default', out: 'public/og-image-v3.png' },
  { key: 'alt', out: 'public/og-image-v3-alt.png' },
  { key: 'v4', out: 'public/og-image-v4.png' },
  { key: 'v4c', out: 'public/og-image-v4-coupon.png' },
]

// ---- 1. Logo paths from the site's components -----------------------------

/** Every <path .../> inside `export function <name>(` up to the next export. */
function pathsOf(file, fnName) {
  const src = readFileSync(resolve(ROOT, file), 'utf8')
  const start = src.indexOf(`export function ${fnName}(`)
  if (start < 0) throw new Error(`${fnName} not found in ${file}`)
  const end = src.indexOf('export function', start + 10)
  const body = src.slice(start, end < 0 ? undefined : end)
  const viewBox = {}
  for (const k of ['VB_X', 'VB_Y', 'VB_W', 'VB_H']) {
    const m = src.match(new RegExp(`const ${k} = ([\\d.]+)`))
    viewBox[k] = Number(m[1])
  }
  const paths = [...body.matchAll(/<path([\s\S]*?)\/>/g)].map(([, attrs]) => {
    const role = attrs.match(/fill=\{(\w+)\}/)[1] // letters | body | lines
    const stroke = attrs.match(/strokeWidth=\{([\d.]+)\}/)
    const d = attrs.match(/d="([^"]+)"/)[1]
    return { role, strokeWidth: stroke ? Number(stroke[1]) : 0, d }
  })
  if (!paths.length) throw new Error(`no paths parsed from ${fnName}`)
  return { viewBox: `${viewBox.VB_X} ${viewBox.VB_Y} ${viewBox.VB_W} ${viewBox.VB_H}`, paths }
}

const logo = {
  full: pathsOf('components/brand/full-logo.tsx', 'FullLogo'),
  plane: pathsOf('components/brand/plane-mark.tsx', 'PlaneMark'),
}
writeFileSync(
  resolve(HERE, 'logo.generated.js'),
  '// GENERATED by scripts/og/render.mjs from components/brand/full-logo.tsx and\n' +
    '// components/brand/plane-mark.tsx. Do not edit; re-run the script.\n' +
    `window.PAPEX_LOGO = ${JSON.stringify(logo)};\n`,
)

// ---- 2. Headless Chrome over CDP ----------------------------------------

const CHROME = process.env.CHROME || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'
const port = 9300 + Math.floor(Math.random() * 500)
const profile = `/tmp/papex-og-${port}`
const chrome = spawn(
  CHROME,
  ['--headless=new', `--remote-debugging-port=${port}`, '--hide-scrollbars', '--no-first-run',
    '--allow-file-access-from-files', `--user-data-dir=${profile}`, `--window-size=${W},${H}`, 'about:blank'],
  { stdio: 'ignore' },
)
const sleep = (ms) => new Promise((r) => setTimeout(r, ms))
let ws
let id = 0
const pending = new Map()
const send = (method, params = {}) =>
  new Promise((res, rej) => {
    const i = ++id
    pending.set(i, { res, rej })
    ws.send(JSON.stringify({ id: i, method, params }))
  })

try {
  let target
  for (let t = 0; t < 40 && !target; t++) {
    await sleep(250)
    try {
      target = (await (await fetch(`http://127.0.0.1:${port}/json`)).json()).find((x) => x.type === 'page')
    } catch {}
  }
  if (!target) throw new Error(`Chrome did not start (${CHROME})`)
  ws = new WebSocket(target.webSocketDebuggerUrl)
  await new Promise((r) => (ws.onopen = r))
  ws.onmessage = (m) => {
    const d = JSON.parse(m.data)
    if (d.id && pending.has(d.id)) {
      const p = pending.get(d.id)
      pending.delete(d.id)
      d.error ? p.rej(new Error(d.error.message)) : p.res(d.result)
    }
  }
  await send('Page.enable')
  await send('Runtime.enable')
  await send('Emulation.setDeviceMetricsOverride', { width: W, height: H, deviceScaleFactor: 1, mobile: false })

  for (const v of VARIANTS) {
    const url = `${pathToFileURL(resolve(HERE, 'og.html')).href}?v=${v.key}`
    await send('Page.navigate', { url })
    // Wait for the page's own "ready" flag (fonts loaded + logo painted).
    let ready = false
    for (let t = 0; t < 60 && !ready; t++) {
      await sleep(100)
      ready = (await send('Runtime.evaluate', { expression: 'window.__ogReady === true', returnByValue: true })).result.value
    }
    if (!ready) throw new Error(`og.html?v=${v.key} never became ready (fonts or logo failed)`)
    await sleep(150)
    const { data } = await send('Page.captureScreenshot', {
      format: 'png',
      clip: { x: 0, y: 0, width: W, height: H, scale: 1 },
    })
    const raw = Buffer.from(data, 'base64')
    let png = await sharp(raw).png({ compressionLevel: 9, adaptiveFiltering: true }).toBuffer()
    if (png.length > MAX_BYTES) {
      png = await sharp(raw).png({ compressionLevel: 9, palette: true, quality: 95, effort: 10, dither: 0.6 }).toBuffer()
    }
    const meta = await sharp(png).metadata()
    if (meta.width !== W || meta.height !== H) throw new Error(`${v.out} is ${meta.width}x${meta.height}`)
    if (png.length > MAX_BYTES) throw new Error(`${v.out} is ${(png.length / 1024).toFixed(0)} KB (> 400 KB)`)
    writeFileSync(resolve(ROOT, v.out), png)
    console.log(`${v.out.padEnd(28)} ${meta.width}x${meta.height}  ${(png.length / 1024).toFixed(0)} KB`)
  }
} catch (e) {
  console.error('render failed:', e.message)
  process.exitCode = 1
} finally {
  try { ws?.close() } catch {}
  chrome.kill('SIGKILL')
  await sleep(200)
  try { rmSync(profile, { recursive: true, force: true }) } catch {}
}
