// GENERATED by scripts/generate-rdh-device.mjs — edit the script, not this file.
import { FullLogo } from "@/components/brand/full-logo";
import styles from "./customer.module.css";

/**
 * The PapeX RDH, as the pilot unit actually ships: a matte-black FDM-printed
 * box (68 x 100 x 42 mm, separate lid, print layer lines), a white PapeX
 * sticker over the front of the lid, a green status LED near the back-right
 * corner, and two USB-C ports on the back end (opposite the sticker) — hidden
 * from this camera, so only the white braided cable leaving one of them is
 * drawn. Reference: Nico's photos of the pilot unit. The orange CAD renders
 * in Papex_RDH_Firmware/docs/enclosure/rdh_final_*.png are a FUTURE enclosure
 * concept, not what ships — don't draw from them.
 *
 * True isometric projection, seen from the front-right (so the /customers hero
 * phone, which overlaps the device's upper-left, never hides the LED). Every
 * marking is drawn in its face's own coordinate matrix so it foreshortens
 * correctly; the sticker carries the real lockup (FullLogo, canonical colours).
 *
 * Inlined (not <img>) so `.rdhLed` can pulse when the hero phone taps down.
 * public/product/rdh-device.svg is the same artwork for /business; both files
 * come from scripts/generate-rdh-device.mjs, so regenerate rather than edit.
 * The cool rim light is deliberate: without it the box vanishes on navy.
 */
export function RdhDevice({ pulsing = false }: { pulsing?: boolean }) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 169.5 138"
      role="img"
      aria-label="The PapeX RDH: a small matte-black box with a white PapeX label on its top, a green status light, and a white USB-C cable plugged into one end."
    >
      <defs>
        <linearGradient id="rdhTopFill" x1="0" y1="1" x2="1" y2="0">
          <stop offset="0" stopColor="#3A3D42" />
          <stop offset="0.5" stopColor="#2A2D31" />
          <stop offset="1" stopColor="#1F2124" />
        </linearGradient>
        <linearGradient id="rdhSideFill" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stopColor="#2B2E33" />
          <stop offset="0.55" stopColor="#1E2023" />
          <stop offset="1" stopColor="#151618" />
        </linearGradient>
        <linearGradient id="rdhSideSweep" x1="0" y1="0" x2="1" y2="0">
          <stop offset="0" stopColor="#FFFFFF" stopOpacity="0.04" />
          <stop offset="0.6" stopColor="#FFFFFF" stopOpacity="0" />
          <stop offset="1" stopColor="#000000" stopOpacity="0.12" />
        </linearGradient>
        <linearGradient id="rdhEndFill" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stopColor="#1D1F22" />
          <stop offset="0.6" stopColor="#141517" />
          <stop offset="1" stopColor="#0D0E0F" />
        </linearGradient>
        <linearGradient id="rdhEdgeDown" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stopColor="#B9CCDF" stopOpacity="0.2" />
          <stop offset="1" stopColor="#B9CCDF" stopOpacity="0" />
        </linearGradient>
        <linearGradient id="rdhEdgeUp" x1="0" y1="1" x2="0" y2="0">
          <stop offset="0" stopColor="#B9CCDF" stopOpacity="0.14" />
          <stop offset="1" stopColor="#B9CCDF" stopOpacity="0" />
        </linearGradient>
        <linearGradient id="rdhEdgeLeft" x1="0" y1="0" x2="1" y2="0">
          <stop offset="0" stopColor="#B9CCDF" stopOpacity="0.13" />
          <stop offset="1" stopColor="#B9CCDF" stopOpacity="0" />
        </linearGradient>
        <linearGradient id="rdhEdgeRight" x1="1" y1="0" x2="0" y2="0">
          <stop offset="0" stopColor="#B9CCDF" stopOpacity="0.14" />
          <stop offset="1" stopColor="#B9CCDF" stopOpacity="0" />
        </linearGradient>
        <pattern id="rdhLayers" width="8" height="1.3" patternUnits="userSpaceOnUse">
          <rect width="8" height="0.3" fill="#FFFFFF" fillOpacity="0.03" />
          <rect y="0.66" width="8" height="0.24" fill="#000000" fillOpacity="0.1" />
        </pattern>
        <pattern id="rdhHatch" width="1.25" height="1.25" patternUnits="userSpaceOnUse" patternTransform="rotate(45)">
          <rect width="0.3" height="1.25" fill="#FFFFFF" fillOpacity="0.02" />
        </pattern>
        <linearGradient id="rdhSticker" x1="0" y1="0" x2="1" y2="1">
          <stop offset="0" stopColor="#F8F8F5" />
          <stop offset="0.6" stopColor="#F3F3F0" />
          <stop offset="1" stopColor="#E8E8E4" />
        </linearGradient>
        <radialGradient id="rdhLedHalo">
          <stop offset="0" stopColor="#3EE584" stopOpacity="0.7" />
          <stop offset="0.35" stopColor="#3EE584" stopOpacity="0.28" />
          <stop offset="1" stopColor="#3EE584" stopOpacity="0" />
        </radialGradient>
        <radialGradient id="rdhLedGlow">
          <stop offset="0" stopColor="#3EE584" stopOpacity="0.5" />
          <stop offset="1" stopColor="#3EE584" stopOpacity="0" />
        </radialGradient>
        <radialGradient id="rdhLedDome" cx="0.4" cy="0.36" r="0.7">
          <stop offset="0" stopColor="#F4FFF8" />
          <stop offset="0.28" stopColor="#B4F9D1" />
          <stop offset="0.62" stopColor="#3EE584" />
          <stop offset="1" stopColor="#16924D" />
        </radialGradient>
        <linearGradient id="rdhCableFade" x1="152.5" y1="72.8" x2="157.18" y2="102.5" gradientUnits="userSpaceOnUse">
          <stop offset="0" stopColor="#000000" />
          <stop offset="0.32" stopColor="#FFFFFF" />
          <stop offset="0.85" stopColor="#FFFFFF" />
          <stop offset="1" stopColor="#000000" />
        </linearGradient>
        <mask id="rdhCableMask" maskUnits="userSpaceOnUse" x="0" y="0" width="169.5" height="138">
          <rect width="169.5" height="138" fill="url(#rdhCableFade)" />
        </mask>
        <clipPath id="rdhBodyClip">
          <path d="M98.2 6.95 Q99.5 6.2 100.8 6.95 L151.2 36.05 Q152.5 36.8 152.5 38.3 L152.5 73.1 Q152.5 74.6 151.2 75.35 L75.86 118.85 Q74.56 119.6 73.26 118.85 L22.86 89.75 Q21.56 89 21.56 87.5 L21.56 52.7 Q21.56 51.2 22.86 50.45 Z" />
        </clipPath>
      </defs>
      <g clipPath="url(#rdhBodyClip)">
        <path d="M99.5 6.2 L152.5 36.8 L152.5 74.6 L74.56 119.6 L21.56 89 L21.56 51.2 Z" fill="#121315" />
        {/* Right long side: the lit face. Print layer lines + lid seam. */}
        <g transform="matrix(0.7794,-0.45,0,0.9,74.5585,81.8)">
          <rect width="100" height="42" fill="url(#rdhSideFill)" />
          <rect width="100" height="42" fill="url(#rdhSideSweep)" />
          <rect width="100" height="42" fill="url(#rdhLayers)" />
          <rect width="100" height="2.6" fill="url(#rdhEdgeDown)" />
          <rect width="2.2" height="42" fill="url(#rdhEdgeLeft)" />
          <path d="M0 4.2 H100" stroke="#040505" strokeWidth="0.55" strokeOpacity="0.9" />
          <path d="M0 4.75 H100" stroke="#FFFFFF" strokeWidth="0.35" strokeOpacity="0.09" />
        </g>
        {/* Front end: plain enclosure — the ports live on the hidden back end. */}
        <g transform="matrix(0.7794,0.45,0,0.9,21.5577,51.2)">
          <rect width="68" height="42" fill="url(#rdhEndFill)" />
          <rect width="68" height="42" fill="url(#rdhLayers)" />
          <rect width="68" height="2.6" fill="url(#rdhEdgeDown)" />
          <rect x="66" width="2" height="42" fill="url(#rdhEdgeRight)" />
          <path d="M0 4.2 H68" stroke="#040505" strokeWidth="0.55" strokeOpacity="0.9" />
          <path d="M0 4.75 H68" stroke="#FFFFFF" strokeWidth="0.35" strokeOpacity="0.07" />
        </g>
        {/* Top face: fine diagonal top-layer infill, eased edges. */}
        <g transform="matrix(-0.7794,0.45,-0.7794,-0.45,152.5008,36.8)">
          <rect width="100" height="68" fill="url(#rdhTopFill)" />
          <rect width="100" height="68" fill="url(#rdhHatch)" />
          <rect x="97.6" width="2.4" height="68" fill="url(#rdhEdgeRight)" />
          <rect width="100" height="2.4" fill="url(#rdhEdgeDown)" />
          <rect width="2" height="68" fill="url(#rdhEdgeLeft)" />
          <rect y="66" width="100" height="2" fill="url(#rdhEdgeUp)" />
        </g>
        {/* Cool rim light on the top edges (keeps the black box off a navy page). */}
        <path d="M21.56 51.2 L99.5 6.2 L152.5 36.8" fill="none" stroke="#B9CCDF" strokeOpacity="0.55" strokeWidth="0.7" strokeLinejoin="round" />
        <path d="M21.56 51.2 L74.56 81.8 L152.5 36.8" fill="none" stroke="#B9CCDF" strokeOpacity="0.5" strokeWidth="0.5" strokeLinejoin="round" />
        <path d="M74.56 81.8 L74.56 119.6" fill="none" stroke="#B9CCDF" strokeOpacity="0.16" strokeWidth="0.5" strokeLinejoin="round" />
        <path d="M21.56 51.56 L21.56 89" fill="none" stroke="#B9CCDF" strokeOpacity="0.2" strokeWidth="0.6" strokeLinejoin="round" />
        <path d="M152.5 37.16 L152.5 74.6" fill="none" stroke="#B9CCDF" strokeOpacity="0.2" strokeWidth="0.6" strokeLinejoin="round" />
      </g>
      <g transform="matrix(-0.7794,0.45,-0.7794,-0.45,152.5008,36.8) matrix(0,-1,1,0,57.1,65.3)">
        <rect x="-0.35" y="-0.2" width="63.3" height="41.25" rx="1.9" fill="#000000" fillOpacity="0.45" />
        <rect width="62.6" height="40.5" rx="1.5" fill="url(#rdhSticker)" />
        <rect width="62.6" height="40.5" rx="1.5" fill="none" stroke="#000000" strokeOpacity="0.12" strokeWidth="0.3" />
        <g transform="translate(5.3,9.88)">
          <FullLogo size={52} letters="#00121D" body="#EB7100" lines="#FFFFFF" />
        </g>
      </g>
      <g transform="matrix(-0.7794,0.45,-0.7794,-0.45,152.5008,36.8)">
        {/* The glow is the element the tap pulses. customer.module.css scales it
            about 29px 59px, so it stays at (29,59) and the wrapper moves it. */}
        <g transform="translate(-9,-44)">
          <circle className={`${styles.rdhLed} ${pulsing ? styles.rdhLedPulsing : ""}`} cx="29" cy="59" r="9" fill="url(#rdhLedHalo)" />
          <circle cx="29" cy="59" r="3.1" fill="#08090A" stroke="#FFFFFF" strokeOpacity="0.1" strokeWidth="0.35" />
        </g>
      </g>
      <circle cx="125.22" cy="38.51" r="4.2" fill="url(#rdhLedGlow)" />
      <ellipse cx="125.22" cy="38.51" rx="2.15" ry="1.75" fill="url(#rdhLedDome)" />
      <ellipse cx="124.67" cy="37.96" rx="0.6" ry="0.42" fill="#FFFFFF" fillOpacity="0.9" />
      {/* White braided cable, emerging from behind the box, dropping onto the */}
      {/* desk and fading in/out at both ends. A faint contact shadow grounds it. */}
      <g mask="url(#rdhCableMask)" fill="none" strokeLinecap="round">
        <path d="M152.5 72.8 C160.29 82.43 161.85 92.6 157.18 102.5" stroke="#000000" strokeWidth="4.6" strokeOpacity="0.1" transform="translate(0,1.6)" />
        <path d="M152.5 72.8 C160.29 82.43 161.85 92.6 157.18 102.5" stroke="#9D9E99" strokeWidth="3.5" transform="translate(0,0.35)" />
        <path d="M152.5 72.8 C160.29 82.43 161.85 92.6 157.18 102.5" stroke="#ECECE8" strokeWidth="3.1" />
        <path d="M152.5 72.8 C160.29 82.43 161.85 92.6 157.18 102.5" stroke="#B5B6B0" strokeWidth="2.9" strokeDasharray="0.42 0.5" strokeOpacity="0.55" />
        <path d="M152.5 72.8 C160.29 82.43 161.85 92.6 157.18 102.5" stroke="#FFFFFF" strokeWidth="2" strokeDasharray="0.25 0.67" strokeDashoffset="0.45" strokeOpacity="0.6" />
        <path d="M152.5 72.8 C160.29 82.43 161.85 92.6 157.18 102.5" stroke="#C9CAC4" strokeWidth="1.1" strokeOpacity="0.55" transform="translate(0,0.95)" />
        <path d="M152.5 72.8 C160.29 82.43 161.85 92.6 157.18 102.5" stroke="#FFFFFF" strokeWidth="0.7" strokeOpacity="0.95" transform="translate(0,-0.8)" />
      </g>
    </svg>
  );
}
