// GENERATED by npm run app:sync from PapeXV2@585e439a (feat/stores-favorites-spacing) + Papex_AppClip@7b516b2b — do not edit by hand
// React Native StyleSheets + constants of the mirrored PapeXV2 components, and the tab bar.
// Re-generate: npm run app:sync   (see docs/design/app-source.md)

/**
 * `rn.<key>.styles.styles.<name>` is the object passed to `StyleSheet.create`
 * in `rn.<key>.file`, with every value resolved to a number/string. Values
 * chosen at runtime (theme colours from hooks, measured sizes) cannot be
 * resolved statically: those properties are ABSENT here and listed in
 * `unresolved` — the web port supplies them from `theme` in tokens.ts.
 */
export const rn = {
  "glassCard": {
    "file": "components/ui/GlassCard.tsx",
    "consts": {},
    "styles": {
      "styles": {
        "clip": {
          "overflow": "hidden"
        },
        "fillHost": {
          "flexGrow": 1
        }
      }
    },
    "unresolved": []
  },
  "glassBubble": {
    "file": "components/ui/GlassBubble.tsx",
    "consts": {
      "HEADER_BUBBLE_HEIGHT": 44,
      "BUBBLE_PADDING_VERTICAL": 8,
      "HEADER_BUBBLE_TITLE_LINE_HEIGHT": 26,
      "HEADER_BUBBLE_TOP": 4,
      "NOTCHED_INSET_MIN": 44,
      "HEADER_BUBBLE_PULL": 2,
      "BUBBLE_RADIUS": 999,
      "FALLBACK_RADIUS": 22,
      "headerBubbleTitle": {
        "fontFamily": "Barlow-Medium",
        "fontSize": 22
      }
    },
    "styles": {
      "styles": {
        "bubble": {},
        "content": {
          "flexDirection": "row",
          "alignItems": "center",
          "gap": 8,
          "paddingHorizontal": 16,
          "paddingVertical": 8
        }
      }
    },
    "unresolved": []
  },
  "glassScreenHeader": {
    "file": "components/ui/GlassScreenHeader.tsx",
    "consts": {
      "HEADER_CIRCLE_ICON": 24,
      "LABELLED_BACK_ICON": 20,
      "HEADER_CONTENT_GAP": 12,
      "GLASS_HEADER_CONTENT_INSET": 60,
      "headerCircle": {
        "bubble": {
          "width": 44,
          "height": 44
        },
        "content": {
          "paddingHorizontal": 0,
          "paddingVertical": 0,
          "gap": 0,
          "justifyContent": "center",
          "alignItems": "center",
          "width": "100%",
          "height": "100%"
        }
      }
    },
    "styles": {
      "styles": {
        "row": {
          "flexDirection": "row",
          "alignItems": "center",
          "alignSelf": "stretch",
          "paddingHorizontal": 16,
          "gap": 10
        },
        "rowTwoLine": {
          "alignItems": "flex-start"
        },
        "side": {
          "flex": 1,
          "alignItems": "flex-start",
          "minWidth": 0
        },
        "sideRight": {
          "alignItems": "flex-end"
        },
        "bubble": {
          "height": 44,
          "justifyContent": "center"
        },
        "titleBubble": {
          "height": 44,
          "justifyContent": "center",
          "flexShrink": 1
        },
        "titleBubbleTwoLine": {
          "justifyContent": "center",
          "flexShrink": 1
        },
        "title": {
          "fontFamily": "Barlow-Medium",
          "fontSize": 22
        },
        "titleTwoLine": {
          "fontFamily": "Barlow-Medium",
          "fontSize": 22,
          "lineHeight": 26,
          "textAlign": "center"
        },
        "backLabel": {
          "fontFamily": "Barlow-Medium",
          "fontSize": 16
        }
      }
    },
    "unresolved": [
      "styles.titleBubbleTwoLine.minHeight = HEADER_BUBBLE_HEIGHT_TWO_LINE"
    ]
  },
  "floatingFab": {
    "file": "components/ui/FloatingFAB.tsx",
    "consts": {
      "FAB_SIZE": 48,
      "ACTION_SIZE": 44,
      "ACTION_GAP": 8,
      "FAB_TO_CLUSTER_GAP": 6,
      "FAB_TO_NAV_GAP": 6
    },
    "styles": {
      "styles": {
        "fabFloat": {
          "position": "absolute",
          "zIndex": 30
        },
        "fab": {
          "width": 48,
          "height": 48,
          "borderRadius": 24,
          "alignItems": "center",
          "justifyContent": "center",
          "borderWidth": 2
        },
        "actionsRow": {
          "position": "absolute",
          "flexDirection": "row",
          "gap": 8,
          "zIndex": 20
        },
        "actionCircle": {
          "width": 44,
          "height": 44,
          "borderRadius": 22,
          "alignItems": "center",
          "justifyContent": "center"
        },
        "captureOverlay": {
          "position": "absolute",
          "left": 0,
          "right": 0,
          "bottom": 0,
          "zIndex": 40,
          "justifyContent": "center",
          "alignItems": "center",
          "paddingHorizontal": 24
        },
        "captureOverlayContent": {
          "alignItems": "center",
          "maxWidth": 320,
          "paddingVertical": 20,
          "paddingHorizontal": 20
        },
        "captureOverlayTitle": {
          "marginTop": 16,
          "fontFamily": "Barlow-Medium",
          "fontSize": 16,
          "textAlign": "center"
        },
        "captureOverlaySubtitle": {
          "marginTop": 6,
          "fontFamily": "Barlow-Regular",
          "fontSize": 14,
          "textAlign": "center",
          "opacity": 0.85
        }
      }
    },
    "unresolved": []
  },
  "segmented": {
    "file": "components/ui/NativeSegmentedControl.tsx",
    "consts": {
      "SYMBOL_SIZE": 17,
      "MINI_SYMBOL_SIZE": 16,
      "COMPACT_WIDTH": 96,
      "MINI_USES_SYSTEM_CONTROL": true,
      "MINI_WIDTH": 80,
      "MINI_HEIGHT": 24,
      "MINI_NATURAL_HEIGHT_GUESS": 32,
      "RESERVED_HEIGHT": {
        "default": 36,
        "compact": 40,
        "mini": 24
      },
      "RESERVED_PER_FONT_SCALE": 18,
      "MIN_REAL_HEIGHT": 16,
      "LOCK_SETTLE_WINDOW_MS": 1000,
      "GLASS_SETTLE_MS": 1200,
      "INTERACTION_QUIET_MS": 500,
      "PRESS_HOLD_MAX_MS": 5000,
      "OVAL_NUDGE_PT": 0.3333333333333333,
      "CAPSULE_EXTRA_BOTTOM_PT": 0.3333333333333333,
      "MEASURED_HEIGHT_KEY": "@papex/nativeSegmentedControl/measuredHeight/v4",
      "MEASURED_HEIGHT_KEY_V1": "@papex/nativeSegmentedControl/measuredHeight/v1",
      "MEASURED_HEIGHT_KEY_V2": "@papex/nativeSegmentedControl/measuredHeight/v2",
      "MEASURED_HEIGHT_KEY_V3": "@papex/nativeSegmentedControl/measuredHeight/v3",
      "NATIVE_MODULE_NAME": "ExpoUI"
    },
    "styles": {
      "boxStyles": {
        "box": {
          "justifyContent": "center"
        }
      },
      "faceStyles": {
        "face": {
          "position": "relative"
        },
        "frost": {
          "position": "absolute",
          "left": 0,
          "right": 0,
          "top": 0,
          "bottom": 0,
          "borderRadius": 9999,
          "overflow": "hidden"
        }
      }
    },
    "unresolved": []
  },
  "tag": {
    "file": "components/ui/pills/Tag.tsx",
    "consts": {
      "GLOW_SCALE": 0.8
    },
    "styles": {
      "styles": {
        "tag": {
          "minHeight": 24,
          "borderRadius": 11.2,
          "paddingHorizontal": 10,
          "gap": 4,
          "flexDirection": "row",
          "alignItems": "center",
          "alignSelf": "flex-start"
        }
      }
    },
    "unresolved": []
  },
  "pillButton": {
    "file": "components/ui/pills/PillButton.tsx",
    "consts": {
      "FACE_TONE": {
        "neutral": "neutral",
        "accent": "attention"
      }
    },
    "styles": {
      "styles": {
        "disabled": {
          "opacity": 0.38
        },
        "body": {
          "flexDirection": "row",
          "alignItems": "center",
          "alignSelf": "flex-start"
        }
      }
    },
    "unresolved": []
  },
  "receiptRow": {
    "file": "components/ui/ReceiptRow.tsx",
    "consts": {
      "LONG_PRESS_MS": 300,
      "PAPEX_ORANGE": "#EB7100",
      "CHECK_BLUE": "#2196F3",
      "TRASH_RED": "#EF4444",
      "RECEIPT_ROW_ACTION_ORANGE": "#EB7100",
      "RECEIPT_ROW_ACTION_RED": "#EF4444",
      "DEFAULT_EDGE_INSET": 16,
      "DEFAULT_ROW_GAP": 12,
      "UNREVIEWED_BAR_INSET": 4,
      "RECEIPT_ROW_CARD_HEIGHT": 91.2,
      "SWIPE_ACTION_WIDTH": 112,
      "SWIPE_OPEN_RATIO": 0.5,
      "SWIPE_COMMIT_RATIO": 0.5,
      "SWIPE_COMMIT_MIN_RATIO_OF_ACTION": 1.25,
      "SWIPE_RUBBER_BAND": 0.75,
      "SWIPE_FLING_COMMIT_VELOCITY": 900,
      "SWIPE_FLING_OPEN_VELOCITY": 300,
      "SWIPE_SPRING": {
        "damping": 20,
        "stiffness": 220,
        "mass": 0.55
      },
      "SWIPE_ARM_SPRING": {
        "damping": 18,
        "stiffness": 260,
        "mass": 0.5
      },
      "SWIPE_GLYPH_RESTING_OPACITY": 0.62,
      "SWIPE_ARM_SCALE": 1.15,
      "SWIPE_FALLBACK_ROW_WIDTH": 340,
      "SWIPE_EDGE_GUARD": 24,
      "SWIPE_BLOCKED_TRAVEL": 16,
      "EXPANDED_ITEM_LIMIT": 8,
      "QUICK_VIEW_PANEL_CHROME": 23,
      "QUICK_VIEW_ROW_GAP": 8,
      "QUICK_VIEW_MORE_PAD": 2,
      "QTY_COL_MIN_WIDTH": 36,
      "QTY_COL_MAX_FONT_SCALE": 2,
      "SWIPE_GLYPH_SIZE": 26,
      "SWIPE_CLUSTER_GAP": 4,
      "SWIPE_CLUSTER_WIDTH": 56,
      "SWIPE_CLUSTER_HEIGHT": 48,
      "SWIPE_TILE_PAD_X": 12,
      "SWIPE_TILE_PAD_Y": 10,
      "SWIPE_TILE_RADIUS": 20,
      "SWIPE_CLUSTER_MAX_FONT_SCALE": 2
    },
    "styles": {
      "styles": {
        "swipeWrapper": {
          "overflow": "hidden"
        },
        "swipeReveal": {
          "position": "absolute",
          "top": 0,
          "bottom": 12,
          "left": 16,
          "right": 16,
          "flexDirection": "row",
          "alignItems": "center",
          "justifyContent": "center"
        },
        "swipeTile": {
          "alignItems": "center",
          "justifyContent": "center",
          "overflow": "hidden"
        },
        "swipeCommitShade": {
          "position": "absolute",
          "left": 0,
          "right": 0,
          "top": 0,
          "bottom": 0,
          "backgroundColor": "rgba(0, 0, 0, 0.22)"
        },
        "swipeActionHit": {
          "flexDirection": "row",
          "alignItems": "center",
          "justifyContent": "center",
          "paddingHorizontal": 10,
          "paddingVertical": 12
        },
        "swipeActionCluster": {
          "position": "absolute",
          "top": 0,
          "left": 0,
          "flexDirection": "column",
          "alignItems": "center",
          "justifyContent": "center",
          "gap": 4
        },
        "swipeRevealText": {
          "fontFamily": "Barlow-Medium",
          "fontSize": 14,
          "textAlign": "center",
          "color": "#fff"
        },
        "receiptCard": {
          "marginHorizontal": 16,
          "marginBottom": 12
        },
        "unreviewedBar": {
          "position": "absolute",
          "left": 4,
          "right": 4,
          "top": 4,
          "bottom": 4,
          "borderRadius": 20,
          "borderLeftWidth": 3,
          "borderColor": "#EB7100",
          "zIndex": 1
        },
        "receiptRow": {
          "flexDirection": "row",
          "alignItems": "center"
        },
        "checkboxContainer": {
          "marginRight": 10,
          "justifyContent": "center"
        },
        "hiddenInSelectMode": {
          "display": "none"
        },
        "selectionRim": {
          "position": "absolute",
          "top": 0,
          "left": 0,
          "right": 0,
          "bottom": 0,
          "borderRadius": 24,
          "borderWidth": 2,
          "borderColor": "#EB7100"
        },
        "checkbox": {
          "width": 24,
          "height": 24,
          "borderRadius": 12,
          "borderWidth": 2,
          "alignItems": "center",
          "justifyContent": "center"
        },
        "logoWithBadge": {
          "position": "relative",
          "marginRight": 12
        },
        "logoWrap": {
          "width": 40,
          "height": 40,
          "borderRadius": 20,
          "borderWidth": 1.5,
          "borderColor": "#EB7100"
        },
        "uncheckedDot": {
          "position": "absolute",
          "bottom": 0,
          "right": 0,
          "width": 10,
          "height": 10,
          "borderRadius": 5,
          "backgroundColor": "#EB7100",
          "borderWidth": 1.5
        },
        "checkedDot": {
          "position": "absolute",
          "bottom": 0,
          "right": 0,
          "width": 14,
          "height": 14,
          "borderRadius": 7,
          "backgroundColor": "#2196F3",
          "alignItems": "center",
          "justifyContent": "center"
        },
        "receiptMain": {
          "flex": 1,
          "minWidth": 0
        },
        "receiptTitleRow": {
          "flexDirection": "row",
          "alignItems": "center",
          "gap": 8,
          "minWidth": 0
        },
        "merchantName": {
          "flex": 1,
          "minWidth": 0,
          "fontFamily": "Barlow-Medium",
          "fontSize": 16
        },
        "originIcon": {
          "width": 28,
          "height": 28,
          "borderRadius": 14,
          "borderWidth": 1,
          "alignItems": "center",
          "justifyContent": "center"
        },
        "originMenuHost": {
          "padding": 8,
          "margin": -8
        },
        "originRow": {
          "flexDirection": "row",
          "alignItems": "center",
          "gap": 6,
          "marginTop": 10
        },
        "expandButton": {
          "width": 28,
          "height": 28,
          "alignItems": "center",
          "justifyContent": "center"
        },
        "chevronMirror": {
          "transform": [
            {
              "scaleX": -1
            }
          ]
        },
        "amount": {
          "fontFamily": "Barlow-Medium",
          "fontSize": 16
        },
        "amountCol": {
          "alignItems": "flex-end",
          "gap": 2
        },
        "meta": {
          "fontFamily": "Barlow-Regular",
          "fontSize": 13,
          "marginTop": 2
        },
        "originDetail": {
          "fontFamily": "Barlow-Medium",
          "fontSize": 12,
          "marginTop": 2
        },
        "statusNote": {
          "fontFamily": "Barlow-Medium",
          "fontSize": 12,
          "marginTop": 2
        },
        "itemsPanel": {
          "marginTop": 12,
          "paddingTop": 10,
          "borderTopWidth": 0.3333333333333333,
          "gap": 8
        },
        "itemRow": {
          "flexDirection": "row",
          "alignItems": "center"
        },
        "itemName": {
          "flex": 1,
          "minWidth": 0,
          "fontFamily": "Barlow-Regular",
          "fontSize": 14
        },
        "itemQty": {
          "flexShrink": 0,
          "paddingLeft": 6,
          "textAlign": "right",
          "fontFamily": "Barlow-Regular",
          "fontSize": 13
        },
        "itemPrice": {
          "flexShrink": 0,
          "minWidth": 64,
          "textAlign": "right",
          "fontFamily": "Barlow-Medium",
          "fontSize": 14
        },
        "itemEmpty": {
          "fontFamily": "Barlow-Regular",
          "fontSize": 13
        },
        "itemsMoreRow": {
          "paddingTop": 2
        },
        "itemsMore": {
          "fontFamily": "Barlow-Medium",
          "fontSize": 13
        }
      }
    },
    "unresolved": []
  },
  "couponRow": {
    "file": "components/coupons/CouponRow.tsx",
    "consts": {
      "COUPON_KIND_META": {
        "bogo": {
          "label": "BOGO",
          "icon": "swap"
        },
        "percent": {
          "label": "% OFF",
          "icon": "pricetag"
        },
        "dollar": {
          "label": "$ OFF",
          "icon": "cash"
        },
        "freebie": {
          "label": "FREE",
          "icon": "gift"
        }
      },
      "DAY_MS": 86400000,
      "RELATIVE_DAY_LIMIT": 30,
      "URGENT_DAY_LIMIT": 3,
      "STORE_NAME_SIZE": 17,
      "TITLE_SIZE": 15,
      "DETAIL_SIZE": 12,
      "TITLE_MIN_FONT_SCALE": 0.75,
      "KIND_CHIP_MIN_HEIGHT": 24,
      "IDENTITY_TO_TITLE_GAP": 1,
      "TEXT_LINE_GAP": 1,
      "ROW_TRAIL_HEIGHT": 28,
      "TRAIL_WIDTH": 62,
      "TRAIL_GAP": 8,
      "BODY_PADDING": 16,
      "BODY_PADDING_LEADING": 14,
      "LIST_EDGE_INSET": 16,
      "BARLOW_AVG_ADVANCE_EM": 0.55,
      "MIN_SIDE_BY_SIDE_GLYPHS": 12,
      "COUPON_ROW_GAP": 12,
      "DETAIL_PANEL_CHROME": 23,
      "DETAIL_ROW_GAP": 8,
      "DETAIL_TEXT_SIZE": 13,
      "DETAIL_EMPTY_TEXT": "No additional details"
    },
    "styles": {
      "styles": {
        "selectOverlay": {
          "position": "absolute",
          "left": 0,
          "right": 0,
          "top": 0,
          "bottom": 0,
          "alignItems": "flex-end",
          "justifyContent": "flex-start",
          "padding": 10
        },
        "selectOverlayHidden": {
          "display": "none"
        },
        "selectRim": {
          "position": "absolute",
          "left": 0,
          "right": 0,
          "top": 0,
          "bottom": 0,
          "borderWidth": 2
        },
        "selectCheckbox": {
          "width": 24,
          "height": 24,
          "borderRadius": 12,
          "borderWidth": 2,
          "alignItems": "center",
          "justifyContent": "center"
        },
        "cardContent": {
          "padding": 0
        },
        "ticket": {
          "flexDirection": "row"
        },
        "ticketStacked": {
          "flexDirection": "column"
        },
        "body": {
          "flex": 1,
          "minWidth": 0,
          "paddingTop": 16,
          "paddingBottom": 16,
          "paddingRight": 16,
          "paddingLeft": 14
        },
        "bodyStacked": {
          "padding": 16
        },
        "mainRow": {
          "flexDirection": "row",
          "alignItems": "center",
          "minHeight": 59.2
        },
        "stackedHeader": {
          "flexDirection": "row",
          "alignItems": "flex-start"
        },
        "dimmed": {
          "opacity": 0.55
        },
        "main": {
          "flex": 1,
          "minWidth": 0
        },
        "identityLine": {
          "flexDirection": "row",
          "flexWrap": "wrap",
          "alignItems": "center",
          "columnGap": 8,
          "rowGap": 4
        },
        "identityLineFixed": {
          "flexDirection": "row",
          "alignItems": "center",
          "columnGap": 8
        },
        "storeName": {
          "fontFamily": "Barlow-Medium",
          "fontSize": 17,
          "flexShrink": 1
        },
        "title": {
          "fontFamily": "Barlow-Regular",
          "fontSize": 15,
          "marginTop": 1
        },
        "detail": {
          "fontFamily": "Barlow-Medium",
          "fontSize": 12,
          "marginTop": 1
        },
        "trailRow": {
          "flexDirection": "row",
          "alignItems": "center",
          "gap": 6,
          "height": 28,
          "marginLeft": 8
        },
        "trailSlot": {
          "width": 28,
          "height": 28,
          "alignItems": "center",
          "justifyContent": "center"
        },
        "chevronMirror": {
          "transform": [
            {
              "scaleX": -1
            }
          ]
        },
        "detailPanel": {
          "marginTop": 12,
          "paddingTop": 10,
          "borderTopWidth": 0.3333333333333333,
          "gap": 8
        },
        "detailRow": {
          "flexDirection": "row",
          "flexWrap": "wrap",
          "alignItems": "baseline",
          "justifyContent": "space-between",
          "columnGap": 12,
          "rowGap": 2
        },
        "detailLabel": {
          "fontFamily": "Barlow-Regular",
          "fontSize": 13
        },
        "detailValue": {
          "flexShrink": 1,
          "textAlign": "right",
          "fontFamily": "Barlow-Medium",
          "fontSize": 13
        },
        "detailParagraph": {
          "fontFamily": "Barlow-Regular",
          "fontSize": 13
        },
        "detailEmpty": {
          "fontFamily": "Barlow-Regular",
          "fontSize": 13
        },
        "heartBox": {
          "alignItems": "center",
          "justifyContent": "center"
        }
      }
    },
    "unresolved": []
  },
  "couponArtwork": {
    "file": "components/coupons/CouponArtwork.tsx",
    "consts": {
      "VARIANTS": {
        "row": {
          "width": 48,
          "aspect": 1,
          "radius": 9,
          "figureScale": 0.3
        },
        "tile": {
          "width": 132,
          "aspect": 1.42,
          "radius": 14,
          "figureScale": 0.3
        },
        "card": {
          "width": 300,
          "aspect": 1.55,
          "radius": 20,
          "figureScale": 0.3
        },
        "hero": {
          "width": 343,
          "aspect": 2.2,
          "radius": 20,
          "figureScale": 0.26
        }
      },
      "MIN_WIDTH_FOR_STUB": 104,
      "MIN_HEIGHT_FOR_CAPTION": 62,
      "STUB_FRACTIONS": [
        0.7,
        0.735,
        0.765
      ],
      "GRADIENT_VECTORS": [
        {
          "x1": "0%",
          "y1": "0%",
          "x2": "100%",
          "y2": "100%"
        },
        {
          "x1": "0%",
          "y1": "100%",
          "x2": "100%",
          "y2": "0%"
        },
        {
          "x1": "0%",
          "y1": "0%",
          "x2": "100%",
          "y2": "35%"
        },
        {
          "x1": "12%",
          "y1": "0%",
          "x2": "88%",
          "y2": "100%"
        }
      ],
      "BAND_STOPS": [
        "38%",
        "50%",
        "62%"
      ],
      "LIT_MIX": 0.12,
      "SHADE_MIX": 0.35,
      "RAMP_SAMPLES_PER_SEGMENT": 8,
      "STRIP_HEIGHT_FRACTION": 0.28,
      "MIN_STRIP_HEIGHT": 14,
      "MAX_STRIP_HEIGHT": 26,
      "STRIP_FIGURE_SCALE": 0.5,
      "STRIP_MIN_INK_CONTRAST": 4.5,
      "STRIP_SHADE_STEPS": [
        0,
        0.1,
        0.2,
        0.3,
        0.4,
        0.5
      ],
      "MONO_ADVANCE_EM": 0.6,
      "STRIP_TRACKING_EM": 0.04,
      "STRIP_FONT_FLOOR": 9,
      "STRIP_FONT_MAX": 14
    },
    "styles": {
      "styles": {
        "overlay": {
          "flexDirection": "row"
        },
        "overlayStrip": {
          "flexDirection": "column"
        },
        "field": {
          "height": "100%",
          "justifyContent": "center"
        },
        "stub": {
          "flex": 1,
          "alignItems": "center",
          "justifyContent": "center",
          "paddingHorizontal": 3
        },
        "strip": {
          "width": "100%",
          "alignItems": "center",
          "justifyContent": "center"
        }
      }
    },
    "unresolved": []
  },
  "brandGlassSurface": {
    "file": "components/coupons/BrandGlassSurface.tsx",
    "consts": {
      "GLASS_ACCENT_ALPHA": {
        "full": 1,
        "mid": 0.45,
        "base": 0.1,
        "border": 0.2,
        "glow": 0.16
      },
      "GLOW_RADIUS": 26,
      "ELLIPSE_RX": "62%",
      "ELLIPSE_RY": "135%",
      "MID_STOP": 0.38,
      "FACE_STRENGTH": 0.82,
      "NEUTRAL_ALPHA": {
        "full": 0.95,
        "mid": 0.3,
        "base": 0.05,
        "border": 0.08
      },
      "BORDER_WIDTH": 1,
      "RING_WIDTH": 1
    },
    "styles": {},
    "unresolved": []
  },
  "couponStoreThumb": {
    "file": "components/coupons/CouponStoreThumb.tsx",
    "consts": {
      "COUPON_STUB_WIDTH": 76,
      "COUPON_STUB_BAND_HEIGHT": 64,
      "LOGO_SIZE": 52,
      "BAND_LOGO_SIZE": 44,
      "MONOGRAM_SIZE": 22,
      "BAND_MONOGRAM_SIZE": 19,
      "NOTCH_R": 7,
      "PERF_DOT": 2.5,
      "PERF_PITCH": 6,
      "PERF_CLEARANCE": 4,
      "COUPON_TICKET_RIM": "none"
    },
    "styles": {
      "styles": {
        "stub": {
          "width": 76,
          "alignSelf": "stretch",
          "alignItems": "center",
          "justifyContent": "center"
        },
        "band": {
          "height": 64,
          "alignSelf": "stretch",
          "alignItems": "flex-start",
          "justifyContent": "center",
          "paddingHorizontal": 16
        },
        "disc": {
          "overflow": "hidden",
          "alignItems": "center",
          "justifyContent": "center"
        },
        "ring": {
          "borderWidth": 1.5
        },
        "notch": {
          "position": "absolute",
          "width": 14,
          "height": 14,
          "borderRadius": 7
        },
        "perf": {
          "position": "absolute"
        }
      }
    },
    "unresolved": []
  },
  "storeTile": {
    "file": "components/coupons/StoreTile.tsx",
    "consts": {
      "STORE_TILE_COLUMNS": 2,
      "STORE_TILE_GAP": 12,
      "STORE_TILE_EDGE_INSET": 16,
      "COVER_HEIGHT": 72,
      "MARK_SIZE": 56,
      "MARK_RING": 3,
      "MARK_INNER": 50,
      "BODY_INSET": 12,
      "BODY_TOP": 36,
      "NAME_LINE_HEIGHT": 20,
      "NAME_LINES": 2,
      "META_GAP": 2,
      "META_LINE_HEIGHT": 18,
      "META_LINES": 2,
      "FOOTER_GAP": 12,
      "FOOTER_PAD": 8,
      "FOOTER_ROW_HEIGHT": 18,
      "STORE_TILE_HEIGHT": 236,
      "MAX_FONT_SCALE": 1.6,
      "MARK_MAX_FONT_SCALE": 1.2,
      "FAVORITE_ACTION": "toggleFavorite",
      "SCRIM": "rgba(0, 0, 0, 0.32)",
      "HEART_DISC": 32,
      "HEART_GLYPH": 18,
      "HEART_TARGET": 44
    },
    "styles": {
      "styles": {
        "cell": {
          "flexGrow": 1
        },
        "card": {
          "flexGrow": 1,
          "minHeight": 236,
          "borderWidth": 0.3333333333333333,
          "overflow": "hidden"
        },
        "cover": {
          "height": 72,
          "paddingTop": 11,
          "paddingLeft": 12,
          "paddingRight": 40,
          "borderBottomWidth": 0.3333333333333333
        },
        "eyebrow": {
          "fontFamily": "IBMPlexMono-Medium",
          "fontSize": 11,
          "letterSpacing": 0.88,
          "textTransform": "uppercase"
        },
        "mark": {
          "position": "absolute",
          "top": 44,
          "left": 12,
          "width": 56,
          "height": 56,
          "padding": 3
        },
        "eyebrowScrim": {
          "alignSelf": "flex-start",
          "paddingHorizontal": 6,
          "borderRadius": 6,
          "overflow": "hidden"
        },
        "favoriteBadge": {
          "position": "absolute",
          "top": 0,
          "right": 0,
          "width": 44,
          "height": 44,
          "alignItems": "center",
          "justifyContent": "center"
        },
        "heartBubble": {
          "width": 32,
          "height": 32
        },
        "body": {
          "flexGrow": 1,
          "paddingTop": 36,
          "paddingHorizontal": 12,
          "paddingBottom": 12
        },
        "name": {
          "fontFamily": "Barlow-SemiBold",
          "fontSize": 16,
          "lineHeight": 20,
          "letterSpacing": -0.2
        },
        "metaBox": {
          "marginTop": 2,
          "marginBottom": 12,
          "justifyContent": "center"
        },
        "meta": {
          "fontFamily": "Barlow-Regular",
          "fontSize": 13,
          "lineHeight": 18
        },
        "offer": {
          "fontFamily": "Barlow-Medium",
          "fontSize": 13,
          "lineHeight": 18
        },
        "footer": {
          "marginTop": "auto",
          "paddingTop": 8,
          "borderTopWidth": 0.3333333333333333,
          "flexDirection": "row",
          "flexWrap": "wrap",
          "alignItems": "center",
          "justifyContent": "space-between",
          "columnGap": 8,
          "rowGap": 4
        },
        "stat": {
          "flexDirection": "row",
          "alignItems": "center",
          "gap": 4,
          "minHeight": 18,
          "flexShrink": 1
        },
        "statText": {
          "fontFamily": "Barlow-Medium",
          "fontSize": 13,
          "lineHeight": 18,
          "flexShrink": 1
        }
      }
    },
    "unresolved": []
  },
  "storeHero": {
    "file": "components/coupons/StoreHero.tsx",
    "consts": {
      "STORE_HERO_BELOW_STATUS": 200,
      "STORE_LOGO_SIZE": 108,
      "LOGO_OVERLAP": 54,
      "LOGO_MAX_FONT_SCALE": 1.3,
      "FADE_START": 0.55
    },
    "styles": {
      "styles": {
        "topScrim": {
          "position": "absolute",
          "top": 0,
          "left": 0,
          "right": 0
        },
        "identity": {
          "alignItems": "center",
          "paddingHorizontal": 8
        },
        "logoShadow": {
          "borderCurve": "continuous",
          "shadowColor": "#000",
          "shadowOpacity": 0.45,
          "shadowRadius": 18,
          "shadowOffset": {
            "width": 0,
            "height": 10
          }
        },
        "name": {
          "fontSize": 30,
          "lineHeight": 34,
          "letterSpacing": -0.6,
          "textAlign": "center",
          "marginTop": 14
        },
        "meta": {
          "marginTop": 4,
          "textAlign": "center"
        },
        "blurb": {
          "marginTop": 6,
          "textAlign": "center",
          "maxWidth": 340
        }
      }
    },
    "unresolved": []
  },
  "storeAppIcon": {
    "file": "components/coupons/StoreAppIcon.tsx",
    "consts": {
      "PAPEX_ICON": {
        "asset": "assets/logos/papex_app_icon.png"
      },
      "APP_ICON_RADIUS_RATIO": 0.225,
      "SQUARE_MIN": 0.8,
      "SQUARE_MAX": 1.25,
      "WORDMARK_INSET": 0.12
    },
    "styles": {
      "styles": {
        "tile": {
          "overflow": "hidden",
          "alignItems": "center",
          "justifyContent": "center",
          "borderCurve": "continuous"
        },
        "rim": {
          "borderWidth": 0.3333333333333333,
          "borderCurve": "continuous"
        }
      }
    },
    "unresolved": []
  },
  "storeBanners": {
    "file": "components/coupons/storeBanners.tsx",
    "consts": {
      "PX_NAVY": "#021D2D",
      "PX_ORANGE": "#EB7100",
      "PX_WHITE": "#F5F5F5",
      "PX_NAVY_LIFT_6": "#112A39",
      "PX_NAVY_LIFT_10": "#1A3341",
      "PX_NAVY_LIFT_14": "#243B49",
      "PX_INK_STOPS": [
        "#021D2D",
        "#0B2534"
      ],
      "PAPEX_BANNERS": [
        {
          "base": [
            "#021D2D",
            "#243B49"
          ],
          "inkStops": [
            "#021D2D",
            "#0B2534"
          ]
        },
        {
          "base": [
            "#021D2D",
            "#1A3341"
          ],
          "inkStops": [
            "#021D2D",
            "#0B2534"
          ]
        },
        {
          "base": [
            "#021D2D",
            "#1A3341"
          ],
          "inkStops": [
            "#021D2D",
            "#0B2534"
          ]
        },
        {
          "base": [
            "#021D2D",
            "#112A39"
          ],
          "inkStops": [
            "#021D2D",
            "#0B2534"
          ]
        },
        {
          "base": [
            "#021D2D",
            "#243B49"
          ],
          "inkStops": [
            "#021D2D",
            "#0B2534"
          ]
        },
        {
          "base": [
            "#021D2D",
            "#1A3341"
          ],
          "inkStops": [
            "#021D2D",
            "#0B2534"
          ]
        }
      ],
      "STORE_BANNERS": {
        "store-doobie-nights": {
          "base": [
            "#2A0B52",
            "#15506A"
          ],
          "inkStops": [
            "#2A0B52",
            "#3A1260"
          ]
        }
      },
      "TOP_WHITE_MIN_CONTRAST": 3,
      "PLATE_COMPACT_MAX": 140
    },
    "styles": {},
    "unresolved": []
  },
  "button": {
    "file": "components/ui/Button.tsx",
    "consts": {
      "SIZE_CONFIG": {
        "sm": {
          "height": 36,
          "paddingHorizontal": 16,
          "fontSize": 14
        },
        "md": {
          "height": 52,
          "paddingHorizontal": 24,
          "fontSize": 17
        },
        "lg": {
          "height": 56,
          "paddingHorizontal": 32,
          "fontSize": 18
        }
      },
      "PRESSED_SCALE": 0.97,
      "PRESSED_OPACITY": 0.85,
      "DISABLED_OPACITY": 0.6
    },
    "styles": {
      "styles": {
        "base": {
          "flexDirection": "row",
          "alignItems": "center",
          "justifyContent": "center",
          "overflow": "hidden"
        },
        "icon": {
          "marginRight": 8
        },
        "text": {
          "fontFamily": "Barlow-SemiBold"
        }
      }
    },
    "unresolved": []
  },
  "merchantLogoImage": {
    "file": "components/ui/MerchantLogoImage.tsx",
    "consts": {},
    "styles": {
      "styles": {
        "fallbackLogoWrap": {
          "alignItems": "center",
          "justifyContent": "center"
        },
        "fallbackLogoImage": {
          "width": "75%",
          "height": "75%"
        },
        "skeleton": {
          "overflow": "hidden"
        }
      }
    },
    "unresolved": []
  },
  "glassIcon": {
    "file": "components/icons/GlassIcon.tsx",
    "consts": {
      "GLASS_SOURCES": {
        "bell": {
          "asset": "assets/icons/glass/bell.png"
        },
        "calendar": {
          "asset": "assets/icons/glass/calendar.png"
        },
        "camera": {
          "asset": "assets/icons/glass/camera.png"
        },
        "car-front": {
          "asset": "assets/icons/glass/car-front.png"
        },
        "cart": {
          "asset": "assets/icons/glass/cart.png"
        },
        "chart-bar": {
          "asset": "assets/icons/glass/chart-bar.png"
        },
        "cloud-download": {
          "asset": "assets/icons/glass/cloud-download.png"
        },
        "cloud-upload": {
          "asset": "assets/icons/glass/cloud-upload.png"
        },
        "credit-cards": {
          "asset": "assets/icons/glass/credit-cards.png"
        },
        "envelope": {
          "asset": "assets/icons/glass/envelope.png"
        },
        "gear": {
          "asset": "assets/icons/glass/gear.png"
        },
        "heart": {
          "asset": "assets/icons/glass/heart.png"
        },
        "heart-off": {
          "asset": "assets/icons/glass/heart-off.png"
        },
        "house": {
          "asset": "assets/icons/glass/house.png"
        },
        "knife-spoon": {
          "asset": "assets/icons/glass/knife-spoon.png"
        },
        "location": {
          "asset": "assets/icons/glass/location.png"
        },
        "lock": {
          "asset": "assets/icons/glass/lock.png"
        },
        "magnifier": {
          "asset": "assets/icons/glass/magnifier.png"
        },
        "medicine": {
          "asset": "assets/icons/glass/medicine.png"
        },
        "miscellaneous": {
          "asset": "assets/icons/glass/miscellaneous.png"
        },
        "money-bill": {
          "asset": "assets/icons/glass/money-bill.png"
        },
        "paper-plane": {
          "asset": "assets/icons/glass/paper-plane.png"
        },
        "pin": {
          "asset": "assets/icons/glass/pin.png"
        },
        "receipt": {
          "asset": "assets/icons/glass/receipt.png"
        },
        "rect-layout-grid": {
          "asset": "assets/icons/glass/rect-layout-grid.png"
        },
        "shopping": {
          "asset": "assets/icons/glass/shopping.png"
        },
        "square-chart-line": {
          "asset": "assets/icons/glass/square-chart-line.png"
        },
        "stack-play": {
          "asset": "assets/icons/glass/stack-play.png"
        },
        "team": {
          "asset": "assets/icons/glass/team.png"
        },
        "wallet-content": {
          "asset": "assets/icons/glass/wallet-content.png"
        }
      },
      "GLASS_SOURCES_LIGHT": {
        "bell": {
          "asset": "assets/icons/glass/bell-light.png"
        },
        "calendar": {
          "asset": "assets/icons/glass/calendar-light.png"
        },
        "camera": {
          "asset": "assets/icons/glass/camera-light.png"
        },
        "car-front": {
          "asset": "assets/icons/glass/car-front-light.png"
        },
        "cart": {
          "asset": "assets/icons/glass/cart-light.png"
        },
        "chart-bar": {
          "asset": "assets/icons/glass/chart-bar-light.png"
        },
        "cloud-download": {
          "asset": "assets/icons/glass/cloud-download-light.png"
        },
        "cloud-upload": {
          "asset": "assets/icons/glass/cloud-upload-light.png"
        },
        "credit-cards": {
          "asset": "assets/icons/glass/credit-cards-light.png"
        },
        "envelope": {
          "asset": "assets/icons/glass/envelope-light.png"
        },
        "gear": {
          "asset": "assets/icons/glass/gear-light.png"
        },
        "heart": {
          "asset": "assets/icons/glass/heart-light.png"
        },
        "heart-off": {
          "asset": "assets/icons/glass/heart-off-light.png"
        },
        "house": {
          "asset": "assets/icons/glass/house-light.png"
        },
        "knife-spoon": {
          "asset": "assets/icons/glass/knife-spoon-light.png"
        },
        "location": {
          "asset": "assets/icons/glass/location-light.png"
        },
        "lock": {
          "asset": "assets/icons/glass/lock-light.png"
        },
        "magnifier": {
          "asset": "assets/icons/glass/magnifier-light.png"
        },
        "medicine": {
          "asset": "assets/icons/glass/medicine-light.png"
        },
        "miscellaneous": {
          "asset": "assets/icons/glass/miscellaneous-light.png"
        },
        "money-bill": {
          "asset": "assets/icons/glass/money-bill-light.png"
        },
        "paper-plane": {
          "asset": "assets/icons/glass/paper-plane-light.png"
        },
        "pin": {
          "asset": "assets/icons/glass/pin-light.png"
        },
        "receipt": {
          "asset": "assets/icons/glass/receipt-light.png"
        },
        "rect-layout-grid": {
          "asset": "assets/icons/glass/rect-layout-grid-light.png"
        },
        "shopping": {
          "asset": "assets/icons/glass/shopping-light.png"
        },
        "square-chart-line": {
          "asset": "assets/icons/glass/square-chart-line-light.png"
        },
        "stack-play": {
          "asset": "assets/icons/glass/stack-play-light.png"
        },
        "team": {
          "asset": "assets/icons/glass/team-light.png"
        },
        "wallet-content": {
          "asset": "assets/icons/glass/wallet-content-light.png"
        }
      },
      "GLASS_SOURCES_BY_MODE": {
        "dark": {
          "bell": {
            "asset": "assets/icons/glass/bell.png"
          },
          "calendar": {
            "asset": "assets/icons/glass/calendar.png"
          },
          "camera": {
            "asset": "assets/icons/glass/camera.png"
          },
          "car-front": {
            "asset": "assets/icons/glass/car-front.png"
          },
          "cart": {
            "asset": "assets/icons/glass/cart.png"
          },
          "chart-bar": {
            "asset": "assets/icons/glass/chart-bar.png"
          },
          "cloud-download": {
            "asset": "assets/icons/glass/cloud-download.png"
          },
          "cloud-upload": {
            "asset": "assets/icons/glass/cloud-upload.png"
          },
          "credit-cards": {
            "asset": "assets/icons/glass/credit-cards.png"
          },
          "envelope": {
            "asset": "assets/icons/glass/envelope.png"
          },
          "gear": {
            "asset": "assets/icons/glass/gear.png"
          },
          "heart": {
            "asset": "assets/icons/glass/heart.png"
          },
          "heart-off": {
            "asset": "assets/icons/glass/heart-off.png"
          },
          "house": {
            "asset": "assets/icons/glass/house.png"
          },
          "knife-spoon": {
            "asset": "assets/icons/glass/knife-spoon.png"
          },
          "location": {
            "asset": "assets/icons/glass/location.png"
          },
          "lock": {
            "asset": "assets/icons/glass/lock.png"
          },
          "magnifier": {
            "asset": "assets/icons/glass/magnifier.png"
          },
          "medicine": {
            "asset": "assets/icons/glass/medicine.png"
          },
          "miscellaneous": {
            "asset": "assets/icons/glass/miscellaneous.png"
          },
          "money-bill": {
            "asset": "assets/icons/glass/money-bill.png"
          },
          "paper-plane": {
            "asset": "assets/icons/glass/paper-plane.png"
          },
          "pin": {
            "asset": "assets/icons/glass/pin.png"
          },
          "receipt": {
            "asset": "assets/icons/glass/receipt.png"
          },
          "rect-layout-grid": {
            "asset": "assets/icons/glass/rect-layout-grid.png"
          },
          "shopping": {
            "asset": "assets/icons/glass/shopping.png"
          },
          "square-chart-line": {
            "asset": "assets/icons/glass/square-chart-line.png"
          },
          "stack-play": {
            "asset": "assets/icons/glass/stack-play.png"
          },
          "team": {
            "asset": "assets/icons/glass/team.png"
          },
          "wallet-content": {
            "asset": "assets/icons/glass/wallet-content.png"
          }
        },
        "light": {
          "bell": {
            "asset": "assets/icons/glass/bell-light.png"
          },
          "calendar": {
            "asset": "assets/icons/glass/calendar-light.png"
          },
          "camera": {
            "asset": "assets/icons/glass/camera-light.png"
          },
          "car-front": {
            "asset": "assets/icons/glass/car-front-light.png"
          },
          "cart": {
            "asset": "assets/icons/glass/cart-light.png"
          },
          "chart-bar": {
            "asset": "assets/icons/glass/chart-bar-light.png"
          },
          "cloud-download": {
            "asset": "assets/icons/glass/cloud-download-light.png"
          },
          "cloud-upload": {
            "asset": "assets/icons/glass/cloud-upload-light.png"
          },
          "credit-cards": {
            "asset": "assets/icons/glass/credit-cards-light.png"
          },
          "envelope": {
            "asset": "assets/icons/glass/envelope-light.png"
          },
          "gear": {
            "asset": "assets/icons/glass/gear-light.png"
          },
          "heart": {
            "asset": "assets/icons/glass/heart-light.png"
          },
          "heart-off": {
            "asset": "assets/icons/glass/heart-off-light.png"
          },
          "house": {
            "asset": "assets/icons/glass/house-light.png"
          },
          "knife-spoon": {
            "asset": "assets/icons/glass/knife-spoon-light.png"
          },
          "location": {
            "asset": "assets/icons/glass/location-light.png"
          },
          "lock": {
            "asset": "assets/icons/glass/lock-light.png"
          },
          "magnifier": {
            "asset": "assets/icons/glass/magnifier-light.png"
          },
          "medicine": {
            "asset": "assets/icons/glass/medicine-light.png"
          },
          "miscellaneous": {
            "asset": "assets/icons/glass/miscellaneous-light.png"
          },
          "money-bill": {
            "asset": "assets/icons/glass/money-bill-light.png"
          },
          "paper-plane": {
            "asset": "assets/icons/glass/paper-plane-light.png"
          },
          "pin": {
            "asset": "assets/icons/glass/pin-light.png"
          },
          "receipt": {
            "asset": "assets/icons/glass/receipt-light.png"
          },
          "rect-layout-grid": {
            "asset": "assets/icons/glass/rect-layout-grid-light.png"
          },
          "shopping": {
            "asset": "assets/icons/glass/shopping-light.png"
          },
          "square-chart-line": {
            "asset": "assets/icons/glass/square-chart-line-light.png"
          },
          "stack-play": {
            "asset": "assets/icons/glass/stack-play-light.png"
          },
          "team": {
            "asset": "assets/icons/glass/team-light.png"
          },
          "wallet-content": {
            "asset": "assets/icons/glass/wallet-content-light.png"
          }
        }
      },
      "GLASS_ALIASES": {
        "grocery": "cart",
        "dining": "knife-spoon",
        "travel": "car-front",
        "healthcare": "medicine",
        "entertainment": "stack-play",
        "misc": "miscellaneous",
        "share": "paper-plane",
        "send": "paper-plane",
        "wallet": "wallet-content",
        "card": "credit-cards",
        "payment": "money-bill",
        "cash": "money-bill",
        "chart": "chart-bar",
        "analytics": "square-chart-line",
        "notification": "bell",
        "search": "magnifier",
        "family": "team",
        "people": "team",
        "privacy": "lock",
        "capture": "camera",
        "home": "house",
        "settings": "gear",
        "mail": "envelope",
        "upload": "cloud-upload",
        "download": "cloud-download",
        "export": "cloud-download",
        "grid": "rect-layout-grid",
        "layout": "rect-layout-grid"
      }
    },
    "styles": {},
    "unresolved": []
  },
  "storeCouponsEmpty": {
    "file": "components/coupons/StoreCouponsEmpty.tsx",
    "consts": {
      "GAP": 8,
      "PREVIEW": 3,
      "SCAN_BUTTON_HEIGHT": 52,
      "SCAN_BUTTON_MARGIN_TOP": 16,
      "TITLE_LINE_HEIGHT": 26,
      "TITLE_CHAR_WIDTH": 9.6,
      "TITLE_MAX_LINES": 3,
      "CAPTION_HEIGHT": 22,
      "PREVIEW_BLOCK_GAP": 16,
      "PREVIEW_LABEL_HEIGHT": 22
    },
    "styles": {
      "styles": {
        "row": {
          "flexDirection": "row",
          "gap": 8
        },
        "scanBlock": {
          "marginTop": 16
        },
        "previewBlock": {
          "marginTop": 16
        }
      }
    },
    "unresolved": []
  },
  "storePointsProgress": {
    "file": "components/coupons/StorePointsProgress.tsx",
    "consts": {
      "TRACK_HEIGHT": 8,
      "NOTCH_WIDTH": 2,
      "TRACK_ALPHA_DARK": 0.1,
      "TRACK_ALPHA_LIGHT": 0.093,
      "CARD_FROST_ALPHA_DARK": 0.07,
      "CARD_FROST_ALPHA_LIGHT": 0.09,
      "FILL_MIN_CONTRAST": 3,
      "INK_MIN_CONTRAST": 4.5,
      "FIGURE_MAX_FONT_SCALE": 1.6
    },
    "styles": {
      "styles": {
        "headerRow": {
          "flexDirection": "row",
          "alignItems": "center",
          "gap": 12
        },
        "flexText": {
          "flexGrow": 1,
          "flexShrink": 1,
          "minWidth": 0
        },
        "figureRow": {
          "flexDirection": "row",
          "alignItems": "baseline",
          "gap": 6,
          "marginTop": 6
        },
        "track": {
          "height": 8,
          "borderRadius": 4,
          "overflow": "hidden",
          "marginTop": 12
        },
        "fill": {
          "position": "absolute",
          "left": 0,
          "right": 0,
          "top": 0,
          "bottom": 0,
          "borderRadius": 4
        },
        "notch": {
          "position": "absolute",
          "top": 0,
          "bottom": 0,
          "width": 2,
          "marginLeft": -1
        },
        "footRow": {
          "flexDirection": "row",
          "alignItems": "baseline",
          "gap": 12,
          "marginTop": 10
        },
        "rewardName": {
          "fontFamily": "Barlow-Medium"
        },
        "goal": {
          "textTransform": "none"
        }
      }
    },
    "unresolved": []
  },
  "storeLoyaltyJoinCard": {
    "file": "components/coupons/StoreLoyaltyJoinCard.tsx",
    "consts": {},
    "styles": {
      "styles": {
        "joinedRow": {
          "flexDirection": "row",
          "alignItems": "center",
          "gap": 8
        },
        "joinedText": {
          "flex": 1
        },
        "subtitle": {
          "marginTop": 4,
          "marginBottom": 12
        },
        "row": {
          "flexDirection": "row",
          "alignItems": "center",
          "gap": 8
        },
        "inputWrap": {
          "flex": 1,
          "flexDirection": "row",
          "alignItems": "center",
          "height": 40,
          "borderWidth": 1,
          "paddingHorizontal": 12
        },
        "inputIcon": {
          "marginRight": 6
        },
        "input": {
          "flex": 1,
          "fontFamily": "Barlow-Regular",
          "fontSize": 14,
          "height": 40,
          "paddingVertical": 0
        },
        "error": {
          "marginTop": 6
        }
      }
    },
    "unresolved": []
  },
  "storeAboutRow": {
    "file": "components/coupons/StoreAboutRow.tsx",
    "consts": {
      "CARD_PADDING": 4,
      "ROW_PADDING_H": 12,
      "HEADER_MIN_HEIGHT": 44,
      "PANEL_PADDING_TOP": 14,
      "PANEL_PADDING_BOTTOM": 12,
      "BLOCK_GAP": 18,
      "HOURS_LIST_TOP": 8,
      "HOURS_ROW_PADDING_V": 4,
      "HOURS_ROW_GAP": 2,
      "HOURS_ROW_GAP_H": 12,
      "HOURS_ROW_PADDING_H": 8,
      "CONTACT_PADDING_V": 10,
      "CONTACT_ICON": 18,
      "CONTACT_GAP": 12,
      "CONTACT_CHEVRON": 16,
      "LEARN_MORE_HEIGHT": 30,
      "BODY_LINE": 22,
      "CAPTION_LINE": 18,
      "SMALL_LINE": 16,
      "EYEBROW_LINE": 16,
      "BODY_GLYPH": 7.5,
      "WRAP_WASTE": 1.15
    },
    "styles": {
      "styles": {
        "header": {
          "minHeight": 44,
          "flexDirection": "row",
          "alignItems": "center",
          "gap": 8,
          "paddingHorizontal": 12
        },
        "headerTitle": {
          "flexShrink": 1
        },
        "statusWrap": {
          "flexGrow": 1,
          "flexShrink": 1,
          "minWidth": 0,
          "flexDirection": "row",
          "alignItems": "center",
          "justifyContent": "flex-end",
          "gap": 6
        },
        "statusDot": {
          "width": 6,
          "height": 6,
          "borderRadius": 3
        },
        "statusText": {
          "flexShrink": 1
        },
        "panel": {
          "borderTopWidth": 0.3333333333333333,
          "paddingTop": 14,
          "paddingBottom": 12,
          "paddingHorizontal": 12
        },
        "blockGap": {
          "marginTop": 18
        },
        "hoursList": {
          "marginTop": 8,
          "gap": 2
        },
        "hoursRow": {
          "borderCurve": "continuous",
          "flexDirection": "row",
          "flexWrap": "wrap",
          "alignItems": "center",
          "justifyContent": "space-between",
          "columnGap": 12,
          "paddingVertical": 4,
          "paddingHorizontal": 8
        },
        "todayWeight": {
          "fontFamily": "Barlow-Medium"
        },
        "contactRow": {
          "flexDirection": "row",
          "alignItems": "center",
          "gap": 12,
          "paddingVertical": 10
        },
        "contactTextColumn": {
          "flexGrow": 1,
          "flexShrink": 1,
          "minWidth": 0
        },
        "contactDetail": {
          "marginTop": 2
        },
        "learnMoreWrap": {
          "paddingVertical": 7,
          "marginVertical": -7
        }
      }
    },
    "unresolved": []
  },
  "receiptsScreen": {
    "file": "app/(tabs)/receipts.tsx",
    "consts": {
      "ALL_CATEGORIES": "__all__",
      "UNCATEGORIZED": "Uncategorized",
      "PAPEX_ORANGE": "#EB7100",
      "BULK_CATEGORY_NONE": "__papex_no_category__",
      "BULK_CATEGORY_NEW": "__papex_new_category__",
      "SEARCH_BAR_HEIGHT": 44,
      "SEARCH_GLYPH": 18,
      "FILTER_PANEL_CHROME": 22,
      "SUGGESTIONS_LIST_MAX": 220,
      "TAP_DISMISS_SLOP": 10,
      "TAP_DISMISS_MAX_MS": 300,
      "SUGGESTIONS_MAX_HEIGHT": 233,
      "HEADER_CONTENT_GAP_BOTTOM": 16,
      "FILTER_BLOCK_PAD_BOTTOM": 12,
      "RECEIPT_ROW_GAP": 12,
      "FILTER_BLOCK_LABEL_GAP": 8,
      "SOURCE_FILTER_OPTIONS": [
        {
          "key": "all",
          "label": "All",
          "icon": "receipt"
        },
        {
          "key": "scanned",
          "label": "Scanned",
          "icon": "scan"
        },
        {
          "key": "email",
          "label": "Email",
          "icon": "mail"
        }
      ],
      "CHECK_FILTER_OPTIONS": [
        {
          "key": "all",
          "label": "All",
          "icon": "receipt"
        },
        {
          "key": "checked",
          "label": "Reviewed",
          "icon": "check-circle"
        },
        {
          "key": "unchecked",
          "label": "Unreviewed",
          "icon": "circle",
          "tone": "attention"
        }
      ],
      "FILTER_PANEL_MAX_BLOCKS": 6,
      "FILTER_PANEL_RADIUS": 16,
      "TRASH_SUMMARY_LIMIT": 4,
      "SHARED_GROUPS_FOCUS_REFETCH_MIN_MS": 10000
    },
    "styles": {
      "styles": {
        "container": {
          "flex": 1
        },
        "headerOverlay": {
          "alignItems": "stretch"
        },
        "header": {
          "flexDirection": "row",
          "alignItems": "center",
          "justifyContent": "space-between",
          "paddingHorizontal": 16,
          "paddingBottom": 8
        },
        "headerTitleRow": {
          "flexDirection": "row",
          "alignItems": "center",
          "gap": 8,
          "flex": 1,
          "minHeight": 44
        },
        "headerSelectBubble": {
          "height": 44,
          "justifyContent": "center"
        },
        "headerSelectLabel": {
          "fontFamily": "Barlow-Medium",
          "fontSize": 17
        },
        "headerTitle": {
          "fontFamily": "Barlow-Medium",
          "fontSize": 22
        },
        "headerTitleCentered": {
          "flexDirection": "row",
          "alignItems": "center",
          "gap": 8
        },
        "headerBubbleStack": {
          "flexDirection": "column",
          "alignItems": "center",
          "gap": 0
        },
        "headerMeta": {
          "flexDirection": "row",
          "alignItems": "baseline",
          "gap": 4
        },
        "uncheckedCount": {
          "fontFamily": "Barlow-Medium",
          "fontSize": 12,
          "color": "#EB710099"
        },
        "uncheckedLabel": {
          "fontFamily": "Barlow-Regular",
          "fontSize": 12,
          "color": "#EB710099"
        },
        "headerActions": {
          "flex": 1,
          "flexDirection": "row",
          "alignItems": "center",
          "justifyContent": "flex-end",
          "gap": 12
        },
        "headerBubble": {
          "minHeight": 44,
          "justifyContent": "center"
        },
        "headerIconButton": {
          "width": 36,
          "height": 36,
          "borderRadius": 18,
          "alignItems": "center",
          "justifyContent": "center"
        },
        "searchRow": {
          "flexDirection": "row",
          "alignItems": "center",
          "gap": 8,
          "paddingHorizontal": 16,
          "paddingTop": 4
        },
        "headerBottomGap": {
          "height": 16
        },
        "filterButtonDisabled": {
          "opacity": 0.35
        },
        "searchBar": {
          "flex": 1,
          "height": 44
        },
        "searchContent": {
          "flex": 1,
          "paddingHorizontal": 12,
          "paddingVertical": 0,
          "gap": 8
        },
        "searchInput": {
          "flex": 1,
          "fontFamily": "Barlow-Regular",
          "fontSize": 15,
          "paddingVertical": 0,
          "height": 44
        },
        "suggestionsLayer": {
          "overflow": "hidden",
          "paddingTop": 5
        },
        "glassFilterPanel": {
          "marginHorizontal": 16,
          "marginBottom": 8,
          "borderRadius": 16,
          "overflow": "hidden",
          "paddingTop": 12,
          "borderWidth": 0
        },
        "filterBlock": {
          "paddingHorizontal": 16,
          "paddingBottom": 12
        },
        "filterTrack": {
          "marginHorizontal": -16
        },
        "filterLabel": {
          "fontFamily": "Barlow-Medium",
          "fontSize": 12,
          "marginBottom": 8
        },
        "groupScopeRow": {
          "paddingHorizontal": 16,
          "paddingBottom": 12
        },
        "pillCentered": {
          "alignSelf": "center"
        },
        "clearText": {
          "fontFamily": "Barlow-Medium",
          "fontSize": 13
        },
        "sectionHeader": {
          "fontFamily": "Barlow-Medium",
          "fontSize": 13,
          "paddingHorizontal": 16,
          "paddingVertical": 8
        },
        "listContent": {},
        "trashSummary": {
          "width": "100%",
          "borderWidth": 1,
          "borderRadius": 18,
          "paddingHorizontal": 12,
          "paddingVertical": 10,
          "gap": 2
        },
        "trashSummaryRow": {
          "flexDirection": "row",
          "alignItems": "center",
          "gap": 8
        },
        "trashSummaryMerchant": {
          "flex": 1,
          "minWidth": 0,
          "fontFamily": "Barlow-Medium",
          "fontSize": 15
        },
        "trashSummaryAmount": {
          "fontFamily": "Barlow-Medium",
          "fontSize": 15
        },
        "trashSummaryMeta": {
          "fontFamily": "Barlow-Regular",
          "fontSize": 13
        },
        "trashSummaryList": {
          "width": "100%",
          "gap": 8
        },
        "trashSummaryMore": {
          "fontFamily": "Barlow-Regular",
          "fontSize": 13,
          "paddingTop": 2
        },
        "skeletonWrap": {
          "marginHorizontal": 16,
          "marginBottom": 12
        },
        "emptyWrap": {
          "paddingTop": 48
        },
        "avatar": {
          "width": 40,
          "height": 40,
          "borderRadius": 20,
          "alignItems": "center",
          "justifyContent": "center",
          "marginRight": 12
        },
        "fallbackLogoWrap": {
          "alignItems": "center",
          "justifyContent": "center"
        },
        "fallbackLogoImage": {
          "width": 30,
          "height": 30
        },
        "pendingShareBar": {
          "flexDirection": "row",
          "alignItems": "center",
          "gap": 8,
          "marginHorizontal": 16,
          "marginTop": -6,
          "marginBottom": 10,
          "paddingHorizontal": 12,
          "paddingVertical": 10,
          "borderWidth": 1,
          "borderRadius": 12,
          "backgroundColor": "rgba(235,113,0,0.10)"
        },
        "pendingShareText": {
          "flex": 1,
          "fontFamily": "Barlow-Regular",
          "fontSize": 13
        },
        "pendingShareButton": {
          "minWidth": 74,
          "paddingVertical": 6,
          "paddingHorizontal": 12,
          "borderRadius": 8,
          "borderWidth": 1,
          "alignItems": "center",
          "justifyContent": "center"
        },
        "pendingShareButtonLabel": {
          "fontFamily": "Barlow-Medium",
          "fontSize": 13
        }
      }
    },
    "unresolved": []
  },
  "couponsScreen": {
    "file": "app/(tabs)/coupons.tsx",
    "consts": {
      "PROMO_BOTTOM_GAP": 16,
      "CONTROLS_FADE_DISTANCE": 40,
      "HEADER_GLASS_ICON": 30,
      "CONTROLS_MIN_SCALE": 0.96,
      "PROMO_PAUSE_OFFSET": 8,
      "COMPACT_PROMO_INSET": 16,
      "PROMO_CHROME_FADE_DISTANCE": 24,
      "PROMO_BED_FADE": [
        0.3,
        0.7
      ],
      "PROMO_FACE_FADE": [
        0.5,
        0.9
      ],
      "PROMO_HANDOFF_STEP": 2,
      "PROMO_MORPH_SAMPLES": 8,
      "TITLE_HIDE_TRAVEL": 30,
      "TITLE_REVEAL_TRAVEL": 6,
      "NOTIF_TOP_INSET": 4,
      "NOTIF_SIDE_MARGIN": 8,
      "NOTIF_ROW_DRIFT": 8,
      "NOTIF_PIN_BLEND": 40,
      "NOTIF_SPRING": {
        "stiffness": 411.20000000000005,
        "damping": 31,
        "mass": 1
      },
      "NOTIF_FADE_TIMING": {
        "duration": 260
      },
      "NOTIF_ROW_HIDE_TIMING": {
        "duration": 180
      },
      "NOTIF_ROW_SHOW_TIMING": {
        "duration": 260
      },
      "HEADER_GLYPH": 18,
      "SEARCH_BAR_HEIGHT": 44,
      "CONTROLS_ROW_HEIGHT": 64,
      "SKELETON_ROWS": 3,
      "SEARCH_DEBOUNCE_MS": 140,
      "TAP_DISMISS_SLOP": 10,
      "TAP_DISMISS_MAX_MS": 300,
      "LIST_WINDOW_SIZE": 3,
      "LIST_INITIAL_ROWS": 6,
      "LIST_BATCH_ROWS": 6
    },
    "styles": {
      "styles": {
        "container": {
          "flex": 1
        },
        "headerOverlay": {
          "alignItems": "stretch"
        },
        "titleRow": {
          "flexDirection": "row",
          "alignItems": "center",
          "paddingHorizontal": 16,
          "paddingBottom": 8
        },
        "headerBubble": {
          "minHeight": 44,
          "justifyContent": "center"
        },
        "headerTitle": {
          "fontFamily": "Barlow-Medium",
          "fontSize": 22
        },
        "titleSide": {
          "flex": 1
        },
        "titleSideLeading": {
          "flexDirection": "row",
          "alignItems": "center",
          "justifyContent": "flex-start"
        },
        "headerSelectTouch": {
          "alignSelf": "flex-start"
        },
        "headerSelectBubble": {
          "height": 44,
          "justifyContent": "center"
        },
        "headerSelectLabel": {
          "fontFamily": "Barlow-Medium",
          "fontSize": 17
        },
        "headerActions": {
          "flexDirection": "row",
          "alignItems": "center",
          "justifyContent": "flex-end",
          "gap": 12
        },
        "controlsRow": {
          "paddingHorizontal": 16,
          "paddingTop": 4,
          "paddingBottom": 16
        },
        "controlsRowInner": {
          "flexDirection": "row",
          "alignItems": "center",
          "gap": 8
        },
        "suggestionsPanel": {
          "marginTop": 5,
          "marginHorizontal": 0
        },
        "badge": {
          "position": "absolute",
          "top": -2,
          "right": -4,
          "borderWidth": 2
        },
        "searchBar": {
          "flex": 1,
          "height": 44
        },
        "searchContent": {
          "flex": 1,
          "paddingHorizontal": 12,
          "paddingVertical": 0,
          "gap": 8
        },
        "searchInput": {
          "flex": 1,
          "fontFamily": "Barlow-Regular",
          "fontSize": 15,
          "paddingVertical": 0,
          "height": 44
        },
        "promoWrap": {
          "marginBottom": 16,
          "zIndex": 1
        },
        "compactPromo": {
          "position": "absolute",
          "left": 16,
          "right": 16,
          "zIndex": 5
        },
        "compactDrop": {
          "position": "absolute",
          "left": 0,
          "right": 0,
          "top": 0,
          "bottom": 0,
          "borderRadius": 24
        },
        "headerLayer": {
          "zIndex": 2
        },
        "cellLayer": {
          "zIndex": 1
        },
        "filterPanel": {
          "paddingHorizontal": 16
        },
        "listRowWrap": {
          "marginHorizontal": 16,
          "marginBottom": 12
        },
        "emptyWrap": {
          "paddingHorizontal": 16,
          "paddingTop": 24
        }
      }
    },
    "unresolved": []
  },
  "couponDetail": {
    "file": "app/couponDetail.tsx",
    "consts": {
      "CODE128_START_B": 104,
      "CODE128_STOP": 106,
      "CODE128_PATTERNS": [
        "212222",
        "222122",
        "222221",
        "121223",
        "121322",
        "131222",
        "122213",
        "122312",
        "132212",
        "221213",
        "221312",
        "231212",
        "112232",
        "122132",
        "122231",
        "113222",
        "123122",
        "123221",
        "223211",
        "221132",
        "221231",
        "213212",
        "223112",
        "312131",
        "311222",
        "321122",
        "321221",
        "312212",
        "322112",
        "322211",
        "212123",
        "212321",
        "232121",
        "111323",
        "131123",
        "131321",
        "112313",
        "132113",
        "132311",
        "211313",
        "231113",
        "231311",
        "112133",
        "112331",
        "132131",
        "113123",
        "113321",
        "133121",
        "313121",
        "211331",
        "231131",
        "213113",
        "213311",
        "213131",
        "311123",
        "311321",
        "331121",
        "312113",
        "312311",
        "332111",
        "314111",
        "221411",
        "431111",
        "111224",
        "111422",
        "121124",
        "121421",
        "141122",
        "141221",
        "112214",
        "112412",
        "122114",
        "122411",
        "142112",
        "142211",
        "241211",
        "221114",
        "413111",
        "241112",
        "134111",
        "111242",
        "121142",
        "121241",
        "114212",
        "124112",
        "124211",
        "411212",
        "421112",
        "421211",
        "212141",
        "214121",
        "412121",
        "111143",
        "111341",
        "131141",
        "114113",
        "114311",
        "411113",
        "411311",
        "113141",
        "114131",
        "311141",
        "411131",
        "211412",
        "211214",
        "211232",
        "2331112"
      ],
      "QUIET_ZONE_MODULES": 10,
      "BARCODE_HEIGHT": 52,
      "CARD_MAX_WIDTH": 440,
      "CARD_RADIUS": 22,
      "GLOW_BLEED_X": 16,
      "GLOW_BLEED_Y": 36,
      "CARD_SKELETON_HEIGHT": 300,
      "PUSH_SETTLE_FALLBACK_MS": 600,
      "STUB_PAPER": "#FFFFFF",
      "ACCENT_MIN_CONTRAST": 3,
      "TERMS_FONT_SIZE": 13,
      "TERMS_LINE_HEIGHT": 18,
      "TERMS_BOTTOM_PAD": 16,
      "TERMS_PAD_X": 4,
      "GLYPH_WIDE": 0.56,
      "GLYPH_NARROW": 0.4
    },
    "styles": {
      "styles": {
        "container": {
          "flex": 1
        },
        "scroll": {
          "flex": 1
        },
        "scrollContent": {
          "paddingHorizontal": 16,
          "gap": 16
        },
        "notFound": {
          "flex": 1
        },
        "cardWrap": {
          "alignSelf": "center"
        },
        "glow": {
          "position": "absolute",
          "left": -16,
          "right": -16,
          "top": -36,
          "bottom": -36
        },
        "cardContent": {
          "paddingTop": 16,
          "paddingHorizontal": 20,
          "paddingBottom": 20
        },
        "storeRow": {
          "flexDirection": "row",
          "alignItems": "center",
          "gap": 12,
          "minHeight": 44,
          "marginBottom": 14
        },
        "storeRowPressed": {
          "opacity": 0.6
        },
        "storeLogo": {
          "width": 40,
          "height": 40
        },
        "storeInitials": {
          "alignItems": "center",
          "justifyContent": "center"
        },
        "storeInitialsText": {
          "fontSize": 15,
          "letterSpacing": -0.3
        },
        "storeText": {
          "flex": 1,
          "gap": 2
        },
        "storeName": {
          "fontSize": 16
        },
        "viewStore": {
          "flexDirection": "row",
          "alignItems": "center",
          "gap": 2
        },
        "metaRow": {
          "flexDirection": "row",
          "alignItems": "center",
          "justifyContent": "space-between",
          "gap": 10
        },
        "expiry": {
          "flexDirection": "row",
          "alignItems": "center",
          "gap": 4,
          "flexShrink": 1
        },
        "expiryText": {
          "fontFamily": "Barlow-Medium",
          "flexShrink": 1
        },
        "title": {
          "fontSize": 26,
          "lineHeight": 30,
          "letterSpacing": -0.5,
          "marginTop": 10
        },
        "subtitle": {
          "marginTop": 2
        },
        "bodyText": {
          "marginTop": 6
        },
        "couponImage": {
          "width": "100%",
          "aspectRatio": 1,
          "marginTop": 12
        },
        "qualifierRow": {
          "flexDirection": "row",
          "flexWrap": "wrap",
          "columnGap": 14,
          "rowGap": 4,
          "marginTop": 10
        },
        "qualifier": {
          "flexDirection": "row",
          "alignItems": "center",
          "gap": 4
        },
        "divider": {
          "height": 0.3333333333333333,
          "marginTop": 16,
          "marginBottom": 14
        },
        "stub": {
          "backgroundColor": "#FFFFFF",
          "paddingHorizontal": 12,
          "paddingVertical": 10,
          "alignItems": "center"
        },
        "barcodePlate": {
          "width": "100%"
        },
        "barcodeCaption": {
          "textAlign": "center",
          "marginTop": 6,
          "letterSpacing": 2
        },
        "codeText": {
          "marginTop": 2,
          "fontSize": 26,
          "letterSpacing": 3
        },
        "termsRow": {
          "flexDirection": "row",
          "alignItems": "center",
          "justifyContent": "space-between",
          "paddingHorizontal": 4,
          "minHeight": 44
        },
        "termsText": {
          "paddingHorizontal": 4,
          "paddingBottom": 16
        },
        "useNowButton": {
          "height": 52,
          "alignItems": "center",
          "justifyContent": "center",
          "overflow": "hidden"
        }
      }
    },
    "unresolved": []
  },
  "storeProfile": {
    "file": "app/store/[id].tsx",
    "consts": {
      "STRIP_ART_WIDTH": 96,
      "SIDE_PADDING": 16,
      "COUPON_GRID_GAP": 16,
      "PREFERENCE_PICTURE": 52,
      "COUPON_RING_WIDTH": 2,
      "COUPON_RING_GAP": 3,
      "SECTION_GAP": 16,
      "PUSH_SETTLE_FALLBACK_MS": 600,
      "MOMENTUM_MAX_MS": 2500,
      "SCROLL_IDLE_MS": 150,
      "MORE_TAB_KEY": "info:*",
      "STORE_TAB_LABEL": {
        "coupons": "Coupons",
        "receipts": "Receipts",
        "menu": "Menu",
        "deals": "Deals",
        "news": "New",
        "events": "Events"
      },
      "FOLDABLE_BUILT_INS": [
        "events",
        "deals"
      ],
      "EMPTY_LIST": [],
      "EMPTY_RECEIPTS": [],
      "RECEIPT_FETCH_LIMIT": 1000
    },
    "styles": {
      "styles": {
        "container": {
          "flex": 1
        },
        "scroll": {
          "flex": 1
        },
        "scrollContent": {
          "paddingHorizontal": 16,
          "gap": 16
        },
        "notFound": {
          "flex": 1
        },
        "heroWash": {
          "position": "absolute",
          "left": 0,
          "right": 0,
          "top": 0,
          "bottom": 0,
          "overflow": "hidden"
        },
        "heroContent": {
          "padding": 12,
          "gap": 12
        },
        "heroCardWrap": {
          "marginTop": 16
        },
        "noDrop": {
          "shadowOpacity": 0,
          "elevation": 0
        },
        "dealStrip": {
          "flexDirection": "row",
          "alignItems": "center",
          "gap": 12
        },
        "dealText": {
          "flexGrow": 1,
          "flexShrink": 1,
          "minWidth": 0
        },
        "sectionCard": {
          "marginTop": 16
        },
        "tabsWrap": {
          "marginTop": 16
        },
        "answeredRow": {
          "flexDirection": "row",
          "alignItems": "flex-start",
          "justifyContent": "space-between",
          "gap": 12
        },
        "answeredTextColumn": {
          "flex": 1,
          "minWidth": 0
        },
        "preferenceEyebrowRow": {
          "flexDirection": "row",
          "alignItems": "center",
          "gap": 6
        },
        "preferenceOptions": {
          "flexDirection": "row",
          "alignItems": "stretch",
          "marginTop": 14
        },
        "preferenceOption": {
          "flex": 1,
          "borderWidth": 1,
          "padding": 12,
          "borderCurve": "continuous"
        },
        "preferenceOr": {
          "width": 30,
          "height": 30,
          "borderRadius": 15,
          "borderWidth": 1,
          "alignSelf": "center",
          "alignItems": "center",
          "justifyContent": "center",
          "marginHorizontal": -9,
          "zIndex": 1
        },
        "preferenceOptionTop": {
          "flexDirection": "row",
          "alignItems": "flex-start",
          "justifyContent": "space-between"
        },
        "preferenceRadio": {
          "width": 18,
          "height": 18,
          "borderRadius": 9,
          "borderWidth": 1.5
        },
        "preferenceSkip": {
          "alignSelf": "center",
          "marginTop": 12
        },
        "sectionEyebrow": {
          "marginBottom": 8
        },
        "hiddenSection": {
          "display": "none"
        },
        "newsGrid": {
          "flexDirection": "row",
          "flexWrap": "wrap",
          "gap": 16
        },
        "couponList": {},
        "listRowWrap": {
          "marginBottom": 12
        },
        "couponHighlightRing": {
          "borderWidth": 2,
          "padding": 3
        },
        "eventsList": {
          "gap": 24
        }
      }
    },
    "unresolved": []
  },
  "receiptDetail": {
    "file": "app/receiptDetail.tsx",
    "consts": {
      "PINNED_GROUPS_STORAGE_KEY": "@pinned_shared_group_ids",
      "PAPEX_ORANGE": "#EB7100",
      "CATEGORY_CREATE_ID": "__create__",
      "CATEGORY_SCROLL_HEADROOM": 96,
      "RECEIPT_MENU_SYMBOLS": {
        "export": "square.and.arrow.up",
        "categorize": "tag",
        "share_group": "person.2",
        "edit": "pencil",
        "delete": "trash",
        "restore": "arrow.uturn.backward"
      },
      "OUTSIDE_TAP_SLOP": 8,
      "EXPANDED_LIST_MAX_HEIGHT": 192,
      "EXPANDED_ROW_HEIGHT": 48,
      "EXPANDED_ROW_MIN_HEIGHT": 44,
      "PEOPLE_INPUT_ROW_HEIGHT": 58,
      "PEOPLE_STAGED_CHIP_LINE_HEIGHT": 30,
      "PEOPLE_STAGED_CHIP_LINE_GAP": 8,
      "PEOPLE_STAGED_BLOCK_CHROME": 70,
      "PEOPLE_ROW_HEIGHT": 56,
      "PEOPLE_LIST_CHROME": 30,
      "PEOPLE_HAIRLINE": 1,
      "SETTLE_MARGIN_MS": 32,
      "MENU_SCROLL_WINDOW_MS": 600,
      "ANCHOR_FIRST_VISIBLE": {
        "minIndexForVisible": 0
      },
      "BARCODE_MAX_HEIGHT": 200,
      "MAX_PLAUSIBLE_TAX_RATE": 12,
      "US_STATE_CODES": [
        "AL",
        "AK",
        "AZ",
        "AR",
        "CA",
        "CO",
        "CT",
        "DE",
        "FL",
        "GA",
        "HI",
        "ID",
        "IL",
        "IN",
        "IA",
        "KS",
        "KY",
        "LA",
        "ME",
        "MD",
        "MA",
        "MI",
        "MN",
        "MS",
        "MO",
        "MT",
        "NE",
        "NV",
        "NH",
        "NJ",
        "NM",
        "NY",
        "NC",
        "ND",
        "OH",
        "OK",
        "OR",
        "PA",
        "RI",
        "SC",
        "SD",
        "TN",
        "TX",
        "UT",
        "VT",
        "VA",
        "WA",
        "WV",
        "WI",
        "WY",
        "DC",
        "PR",
        "VI",
        "GU",
        "AS",
        "MP"
      ],
      "PLACEHOLDER_FILE_NAMES": [
        "receipt.jpg",
        "receipt.jpeg",
        "receipt.png",
        "receipt.pdf",
        "image.jpg",
        "image.jpeg",
        "image.png",
        "photo.jpg",
        "manual-entry.jpg",
        "untitled"
      ],
      "PAYMENT_METHOD_STYLES": {
        "visa": {
          "label": "VISA"
        },
        "mastercard": {
          "label": "MASTERCARD"
        },
        "amex": {
          "label": "AMEX"
        },
        "discover": {
          "label": "DISCOVER"
        },
        "diners_club": {
          "label": "DINERS"
        },
        "jcb": {
          "label": "JCB"
        },
        "unionpay": {
          "label": "UNIONPAY"
        },
        "maestro": {
          "label": "MAESTRO"
        },
        "apple_pay": {
          "label": "APPLE PAY"
        },
        "google_pay": {
          "label": "G PAY"
        },
        "paypal": {
          "label": "PAYPAL"
        },
        "venmo": {
          "label": "VENMO"
        },
        "cash_app": {
          "label": "CASH APP"
        },
        "cash": {
          "label": "CASH"
        },
        "ebt": {
          "label": "EBT"
        },
        "check": {
          "label": "CHECK"
        }
      },
      "PDF_IMAGE_MAX_EDGE_PX": 1400,
      "PDF_IMAGE_JPEG_QUALITY": 0.8,
      "PDF_LOGO_FETCH_TIMEOUT_MS": 2500
    },
    "styles": {
      "styles": {
        "container": {
          "flex": 1
        },
        "backButton": {
          "width": 40,
          "height": 40,
          "borderRadius": 20,
          "justifyContent": "center",
          "alignItems": "center"
        },
        "headerTitle": {
          "fontSize": 20,
          "fontFamily": "Barlow-Medium"
        },
        "menuButton": {
          "width": 28,
          "height": 34,
          "borderRadius": 17,
          "alignItems": "center",
          "justifyContent": "center",
          "marginRight": 4
        },
        "storeSection": {
          "padding": 20
        },
        "storeHeader": {
          "flexDirection": "row",
          "alignItems": "center",
          "justifyContent": "center"
        },
        "storeIcon": {
          "width": 48,
          "height": 48,
          "borderRadius": 24,
          "justifyContent": "center",
          "alignItems": "center",
          "marginRight": 12,
          "borderWidth": 2,
          "overflow": "hidden"
        },
        "merchantLogoImage": {
          "width": "100%",
          "height": "100%"
        },
        "storeName": {
          "fontSize": 24,
          "fontFamily": "Barlow-Medium",
          "flexShrink": 1
        },
        "storeDivider": {
          "height": 1,
          "marginHorizontal": 24,
          "marginTop": 16,
          "marginBottom": 14
        },
        "storeMeta": {
          "alignItems": "stretch"
        },
        "storeAddress": {
          "fontSize": 14,
          "fontFamily": "Barlow-Regular",
          "textAlign": "center",
          "marginBottom": 4
        },
        "receiptDateTime": {
          "fontSize": 12,
          "fontFamily": "Barlow-Light",
          "textAlign": "center"
        },
        "receiptTypeRow": {
          "flexDirection": "row",
          "alignItems": "center",
          "justifyContent": "center",
          "gap": 8,
          "marginTop": 4,
          "flexWrap": "wrap"
        },
        "receiptType": {
          "fontSize": 10,
          "fontFamily": "Barlow-Regular",
          "textAlign": "center"
        },
        "itemsSection": {
          "paddingHorizontal": 20,
          "marginBottom": 20
        },
        "sectionTitle": {
          "fontSize": 20,
          "fontFamily": "Barlow-Medium",
          "marginBottom": 16
        },
        "itemRow": {
          "flexDirection": "row",
          "justifyContent": "space-between",
          "alignItems": "center",
          "paddingVertical": 12,
          "borderBottomWidth": 1
        },
        "itemRowModifier": {
          "paddingLeft": 16,
          "paddingVertical": 5
        },
        "itemRowNoDivider": {
          "borderBottomWidth": 0
        },
        "itemLeft": {
          "flex": 1,
          "marginRight": 16
        },
        "itemName": {
          "fontSize": 16,
          "fontFamily": "Barlow-Medium",
          "marginBottom": 6
        },
        "itemNameModifier": {
          "fontSize": 14,
          "fontFamily": "Barlow-Regular"
        },
        "itemSku": {
          "fontSize": 15,
          "fontFamily": "Barlow-Regular",
          "marginLeft": 4
        },
        "itemRight": {
          "alignItems": "flex-end"
        },
        "itemQuantity": {
          "fontSize": 12,
          "fontFamily": "Barlow-Regular",
          "marginBottom": 2
        },
        "itemPrice": {
          "fontSize": 16,
          "fontFamily": "Barlow-Medium"
        },
        "totalSection": {
          "paddingHorizontal": 20,
          "marginBottom": 20
        },
        "totalRow": {
          "flexDirection": "row",
          "justifyContent": "space-between",
          "alignItems": "center",
          "paddingVertical": 8
        },
        "finalTotal": {
          "borderTopWidth": 2,
          "marginTop": 8,
          "paddingTop": 16
        },
        "totalLabel": {
          "fontSize": 16,
          "fontFamily": "Barlow-Regular"
        },
        "totalValue": {
          "fontSize": 16,
          "fontFamily": "Barlow-Medium"
        },
        "totalLabelFinal": {
          "fontSize": 20,
          "fontFamily": "Barlow-Medium"
        },
        "totalValueFinal": {
          "fontSize": 24,
          "fontFamily": "Barlow-Medium"
        },
        "paymentRow": {
          "flexDirection": "row",
          "alignItems": "center",
          "gap": 8
        },
        "barcodeSection": {
          "paddingHorizontal": 20,
          "marginBottom": 30
        },
        "barcodeContainer": {
          "borderRadius": 24,
          "padding": 24,
          "alignItems": "center"
        },
        "barcodeLines": {
          "flexDirection": "row",
          "alignItems": "flex-end",
          "justifyContent": "center",
          "marginBottom": 12,
          "height": 60
        },
        "barcodeNumber": {
          "fontSize": 14,
          "fontFamily": "Barlow-Medium",
          "letterSpacing": 2
        },
        "barcodeRevealButton": {
          "flexDirection": "row",
          "alignItems": "center",
          "gap": 10,
          "paddingHorizontal": 16,
          "paddingVertical": 14
        },
        "barcodeCardContent": {
          "padding": 0
        },
        "barcodeRevealText": {
          "flex": 1,
          "fontFamily": "Barlow-Medium",
          "fontSize": 15
        },
        "barcodeRevealHeader": {
          "flexDirection": "row",
          "alignItems": "center",
          "justifyContent": "space-between",
          "marginBottom": 12
        },
        "metadataSection": {
          "paddingHorizontal": 20,
          "marginBottom": 20
        },
        "metadataRow": {
          "flexDirection": "row",
          "justifyContent": "space-between",
          "alignItems": "center",
          "paddingVertical": 8,
          "borderBottomWidth": 1
        },
        "metadataLabel": {
          "fontSize": 14,
          "fontFamily": "Barlow-Medium",
          "fontWeight": "500"
        },
        "metadataValue": {
          "fontSize": 14,
          "fontFamily": "Barlow-Medium",
          "textAlign": "right",
          "flex": 1,
          "marginLeft": 16
        },
        "imageSection": {
          "paddingHorizontal": 20,
          "marginBottom": 20
        },
        "imageContainer": {
          "borderRadius": 24,
          "padding": 16,
          "overflow": "hidden",
          "position": "relative"
        },
        "receiptImage": {
          "width": "100%",
          "height": 300,
          "borderRadius": 16
        },
        "receiptImagePrimary": {
          "width": "100%",
          "height": 480,
          "borderRadius": 16
        },
        "imageOverlay": {
          "position": "absolute",
          "bottom": 16,
          "left": 16,
          "right": 16,
          "backgroundColor": "rgba(0,0,0,0.6)",
          "padding": 12,
          "borderRadius": 8,
          "flexDirection": "row",
          "alignItems": "center",
          "justifyContent": "center",
          "gap": 8
        },
        "imageOverlayText": {
          "color": "#FFFFFF",
          "fontSize": 14,
          "fontFamily": "Barlow-Medium"
        },
        "imageViewerContainer": {
          "flex": 1,
          "backgroundColor": "rgba(0,0,0,0.95)"
        },
        "imageViewerSafeArea": {
          "flex": 1
        },
        "imageViewerHeader": {
          "flexDirection": "row",
          "justifyContent": "space-between",
          "alignItems": "center",
          "paddingHorizontal": 20,
          "paddingVertical": 16,
          "backgroundColor": "rgba(0,0,0,0.8)"
        },
        "imageViewerCloseButton": {
          "width": 40,
          "height": 40,
          "justifyContent": "center",
          "alignItems": "center"
        },
        "imageViewerTitle": {
          "fontSize": 18,
          "fontFamily": "Barlow-Medium",
          "color": "#FFFFFF"
        },
        "imageViewerScrollContent": {
          "flexGrow": 1,
          "justifyContent": "center",
          "alignItems": "center"
        },
        "fullScreenImage": {},
        "categorySection": {
          "paddingHorizontal": 20,
          "marginBottom": 20
        },
        "suggestionCard": {
          "marginTop": 10
        },
        "suggestionCardContent": {
          "paddingHorizontal": 14,
          "paddingVertical": 12,
          "gap": 12
        },
        "suggestionHeader": {
          "flexDirection": "row",
          "alignItems": "center",
          "gap": 8
        },
        "suggestionText": {
          "flex": 1,
          "fontFamily": "Barlow-Medium",
          "fontSize": 14
        },
        "suggestionActions": {
          "flexDirection": "row",
          "justifyContent": "flex-end",
          "gap": 10
        },
        "suggestionButton": {
          "minWidth": 76,
          "paddingVertical": 8,
          "paddingHorizontal": 16,
          "borderRadius": 8,
          "borderWidth": 1,
          "alignItems": "center",
          "justifyContent": "center"
        },
        "suggestionButtonLabel": {
          "fontFamily": "Barlow-Medium",
          "fontSize": 14
        },
        "categoryCardContent": {
          "padding": 0
        },
        "categoryButton": {
          "flexDirection": "row",
          "alignItems": "center",
          "padding": 16,
          "gap": 12
        },
        "expandList": {
          "maxHeight": 192
        },
        "expandListContent": {
          "flexGrow": 0
        },
        "expandRow": {
          "flexDirection": "row",
          "alignItems": "center",
          "gap": 12,
          "paddingHorizontal": 16,
          "paddingVertical": 13,
          "borderTopWidth": 0.3333333333333333
        },
        "expandRowLabel": {
          "flex": 1,
          "fontSize": 15,
          "fontFamily": "Barlow-Medium"
        },
        "categoryText": {
          "flex": 1,
          "fontSize": 16,
          "fontFamily": "Barlow-Medium"
        },
        "personInputRow": {
          "flexDirection": "row",
          "alignItems": "center",
          "gap": 12,
          "paddingHorizontal": 16,
          "paddingVertical": 7
        },
        "personInput": {
          "flex": 1,
          "minHeight": 44,
          "fontFamily": "Barlow-Regular",
          "fontSize": 16,
          "paddingVertical": 0,
          "paddingHorizontal": 0
        },
        "personDivider": {
          "height": 1,
          "marginHorizontal": 16
        },
        "personStagedBlock": {
          "paddingHorizontal": 16,
          "paddingTop": 12,
          "paddingBottom": 16,
          "gap": 12
        },
        "stagedRow": {
          "flexDirection": "row",
          "flexWrap": "wrap",
          "gap": 8,
          "paddingVertical": 7,
          "marginVertical": -7
        },
        "stagedChip": {
          "maxWidth": 200
        },
        "personCommitButton": {
          "alignSelf": "stretch"
        },
        "pendingShareSection": {
          "paddingHorizontal": 20,
          "paddingTop": 8,
          "marginBottom": 20
        },
        "pendingShareCardContent": {
          "padding": 16,
          "gap": 12
        },
        "pendingShareHeader": {
          "flexDirection": "row",
          "alignItems": "center",
          "gap": 12
        },
        "pendingShareTitle": {
          "fontFamily": "Barlow-Medium",
          "fontSize": 15
        },
        "pendingShareBody": {
          "fontFamily": "Barlow-Regular",
          "fontSize": 13,
          "marginTop": 2
        },
        "pendingShareActions": {
          "flexDirection": "row",
          "justifyContent": "flex-end"
        },
        "personList": {
          "paddingTop": 14,
          "paddingBottom": 16
        },
        "personRow": {
          "flexDirection": "row",
          "alignItems": "center",
          "gap": 12,
          "paddingHorizontal": 16,
          "paddingVertical": 10,
          "minHeight": 56
        },
        "personRowDivider": {
          "height": 1,
          "marginLeft": 64,
          "marginRight": 16
        },
        "personRowText": {
          "flex": 1
        },
        "personRowName": {
          "fontFamily": "Barlow-Medium",
          "fontSize": 16
        },
        "personRowStatus": {
          "fontFamily": "Barlow-Regular",
          "fontSize": 13,
          "marginTop": 1
        },
        "personRowAvatar": {
          "width": 36,
          "height": 36,
          "borderRadius": 18,
          "alignItems": "center",
          "justifyContent": "center",
          "overflow": "hidden"
        },
        "personRowAvatarImage": {
          "width": "100%",
          "height": "100%"
        },
        "personAvatarLetter": {
          "fontFamily": "Barlow-Medium",
          "fontSize": 15
        },
        "familySharingSubtext": {
          "fontSize": 12,
          "fontFamily": "Barlow-Regular",
          "marginTop": 2
        },
        "sharedSummaryRow": {
          "flex": 1,
          "flexDirection": "row",
          "flexWrap": "wrap",
          "alignItems": "center"
        },
        "sharedSummaryText": {
          "flex": 0
        },
        "sharedSummarySegment": {
          "flexDirection": "row",
          "alignItems": "center"
        },
        "sharedSummaryPin": {
          "marginLeft": 3,
          "marginRight": 1
        }
      }
    },
    "unresolved": [
      "styles.fullScreenImage.width = width",
      "styles.fullScreenImage.height = width * 1.5"
    ]
  }
} as const;

/** The system tab bar, read from `app/(tabs)/_layout.tsx`. Icon URLs are the synced @2x copies. */
export const navigation = {
  "file": "app/(tabs)/_layout.tsx",
  "tabs": [
    {
      "name": "home",
      "label": "Home",
      "icons": {
        "darkDefault": "/app/kit/icons/tabbar/house-inactive@2x.png",
        "darkSelected": "/app/kit/icons/tabbar/house@2x.png",
        "lightDefault": "/app/kit/icons/tabbar/house-inactive-light@2x.png",
        "lightSelected": "/app/kit/icons/tabbar/house-light@2x.png"
      }
    },
    {
      "name": "receipts",
      "label": "Receipts",
      "icons": {
        "darkDefault": "/app/kit/icons/tabbar/receipt-inactive@2x.png",
        "darkSelected": "/app/kit/icons/tabbar/receipt@2x.png",
        "lightDefault": "/app/kit/icons/tabbar/receipt-inactive-light@2x.png",
        "lightSelected": "/app/kit/icons/tabbar/receipt-light@2x.png"
      }
    },
    {
      "name": "coupons",
      "label": "Coupons",
      "icons": {
        "darkDefault": "/app/kit/icons/tabbar/coupon-inactive@2x.png",
        "darkSelected": "/app/kit/icons/tabbar/coupon@2x.png",
        "lightDefault": "/app/kit/icons/tabbar/coupon-inactive-light@2x.png",
        "lightSelected": "/app/kit/icons/tabbar/coupon-light@2x.png"
      }
    },
    {
      "name": "stores",
      "label": "Stores",
      "icons": {
        "darkDefault": "/app/kit/icons/tabbar/cart-inactive@2x.png",
        "darkSelected": "/app/kit/icons/tabbar/cart@2x.png",
        "lightDefault": "/app/kit/icons/tabbar/cart-inactive-light@2x.png",
        "lightSelected": "/app/kit/icons/tabbar/cart-light@2x.png"
      }
    },
    {
      "name": "settings",
      "label": "Settings",
      "icons": {
        "darkDefault": "/app/kit/icons/tabbar/gear-inactive@2x.png",
        "darkSelected": "/app/kit/icons/tabbar/gear@2x.png",
        "lightDefault": "/app/kit/icons/tabbar/gear-inactive-light@2x.png",
        "lightSelected": "/app/kit/icons/tabbar/gear-light@2x.png"
      }
    }
  ],
  "fabTabs": [
    "home",
    "receipts"
  ],
  "tintColorToken": "orange",
  "tintColor": "#EB7100",
  "minimizeBehavior": "never"
} as const;
