// GENERATED by npm run app:sync from PapeXV2@585e439a (feat/stores-favorites-spacing) + Papex_AppClip@7b516b2b — do not edit by hand
// Design tokens: PapeXV2 theme/tokens.ts (+ motion, pills, tab-bar metrics) and the App Clip theme.
// Re-generate: npm run app:sync   (see docs/design/app-source.md)

/** Where these values came from. */
export const SOURCE = {
  "papexv2": {
    "commit": "585e439aa9bc82d7b4879ad9fdebfcbd3da86943",
    "short": "585e439a",
    "branch": "feat/stores-favorites-spacing",
    "uncommitted": []
  },
  "appclip": {
    "commit": "7b516b2bf47f1fa67aff0a631f6f0e89edb795ef",
    "short": "7b516b2b",
    "branch": "receipt-design",
    "uncommitted": []
  },
  "evalDevice": {
    "os": "ios",
    "width": 393,
    "height": 852,
    "scale": 3,
    "fontScale": 1
  }
} as const;

/** PapeXV2 `theme/tokens.ts` — every exported value that is data. */
export const theme = {
  "AMBIENT_LIFT_LIGHT": "0 1px 3px rgba(0, 18, 29, 0.05), 0 6px 20px rgba(0, 18, 29, 0.06)",
  "COLOR_KEY_PARITY": true,
  "EDGE_FADE_REACH": 0.6,
  "EDGE_INTENSITY": 0.6,
  "RESTING_LIFT_LIGHT": "0 1px 2px rgba(0, 18, 29, 0.035), 0 4px 12px rgba(0, 18, 29, 0.04)",
  "RIM_SHAPE_LIGHT": "diagonal",
  "RIM_U_BOTTOM_DIP": 0.5,
  "RING_PLATEAU": 0.55,
  "accentByMode": {
    "dark": {
      "accent": "#FFFFFF",
      "ground": "#00121D",
      "chosen": "#0088EA",
      "atmosphere": "#EB7100",
      "invariant": "#EB7100",
      "rim": {
        "lit": 0.51,
        "faint": 0.153
      },
      "pill": {
        "full": 0.95,
        "mid": 0.3,
        "face": 0.05
      }
    },
    "light": {
      "accent": "#00121D",
      "ground": "#FFFFFF",
      "chosen": "#00121D",
      "atmosphere": "#0088EA",
      "invariant": "#EB7100",
      "rim": {
        "lit": 0.28,
        "faint": 0.084
      },
      "pill": {
        "full": 0.42,
        "mid": 0.16,
        "face": 0.05
      }
    }
  },
  "chartPalette": [
    "#EB7100",
    "#2E86C1",
    "#5DADE2",
    "rgba(255, 255, 255, 0.55)",
    "rgba(255, 255, 255, 0.34)",
    "rgba(255, 255, 255, 0.18)"
  ],
  "chartPaletteByMode": {
    "dark": [
      "#EB7100",
      "#2E86C1",
      "#5DADE2",
      "rgba(255, 255, 255, 0.55)",
      "rgba(255, 255, 255, 0.34)",
      "rgba(255, 255, 255, 0.18)"
    ],
    "light": [
      "#EB7100",
      "#2E86C1",
      "#5DADE2",
      "rgba(0, 18, 29, 0.66)",
      "rgba(0, 18, 29, 0.45)",
      "rgba(0, 18, 29, 0.23)"
    ]
  },
  "colors": {
    "orange": "#EB7100",
    "orangeLight": "#EB7100",
    "navy": "#00121D",
    "blue": "#0088EA",
    "blueDark": "#1E4A7B",
    "standardOutline": "#7FC4EC",
    "orangeDeep": "#A85200",
    "white": "#FFFFFF",
    "black": "#000000",
    "success": "#34C759",
    "error": "#FF3B30",
    "warning": "#FFB800",
    "info": "#0088EA"
  },
  "colorsDark": {
    "orange": "#EB7100",
    "orangeLight": "#EB7100",
    "navy": "#00121D",
    "blue": "#0088EA",
    "blueDark": "#1E4A7B",
    "standardOutline": "#7FC4EC",
    "orangeDeep": "#A85200",
    "white": "#FFFFFF",
    "black": "#000000",
    "success": "#34C759",
    "error": "#FF3B30",
    "warning": "#FFB800",
    "info": "#0088EA",
    "orange20": "rgba(235, 113, 0, 0.20)",
    "orange12": "rgba(235, 113, 0, 0.12)",
    "orange08": "rgba(235, 113, 0, 0.08)",
    "text": "rgba(255, 255, 255, 0.90)",
    "textSecondary": "rgba(255, 255, 255, 0.64)",
    "textMuted": "rgba(255, 255, 255, 0.45)",
    "background": "#00121D",
    "surface": "#2C2C2C",
    "cardBackground": "#2C2C2C",
    "primary": "#EB7100",
    "primaryDark": "#D65E00",
    "accent": "#EB7100",
    "accentLight": "#EB7100",
    "tint": "#EB7100",
    "icon": "rgba(255, 255, 255, 0.64)",
    "tabIconDefault": "rgba(255, 255, 255, 0.45)",
    "tabIconSelected": "#EB7100",
    "border": "rgba(255, 255, 255, 0.09)",
    "borderLight": "rgba(255, 255, 255, 0.06)",
    "inputBackground": "rgba(255, 255, 255, 0.08)",
    "inputBorder": "rgba(255, 255, 255, 0.12)",
    "divider": "rgba(255, 255, 255, 0.10)",
    "buttonText": "#FFFFFF",
    "socialBackground": "rgba(255, 255, 255, 0.06)",
    "brandText": "#EB7100",
    "accentText": "#EB7100",
    "lightBlueBg": "rgba(0, 136, 234, 0.12)",
    "orangeBg": "rgba(235, 113, 0, 0.08)",
    "darkCard": "#00121D",
    "receiptCardBed": "#00121D",
    "brandGradient": [
      "#3E6076",
      "#3E6076"
    ],
    "accentGradient": [
      "#EB7100",
      "#EB7100"
    ],
    "brandMixed": [
      "#EB7100",
      "#EB7100"
    ],
    "chosen": "#0088EA",
    "attention": "#EB7100",
    "orangeInk": "#EB7100",
    "ambient": "#EB7100",
    "onFill": "rgba(0, 18, 29, 0.75)",
    "tileBackground": "rgba(255,255,255,0.10)",
    "tileIcon": "rgba(255,255,255,0.90)",
    "inkOnFill": "#FFFFFF",
    "destructiveText": "#FF453A",
    "warningText": "#FFB800",
    "successText": "#34C759"
  },
  "colorsLight": {
    "orange": "#EB7100",
    "orangeLight": "#EB7100",
    "navy": "#00121D",
    "blue": "#0088EA",
    "blueDark": "#1E4A7B",
    "standardOutline": "#7FC4EC",
    "orangeDeep": "#A85200",
    "white": "#FFFFFF",
    "black": "#000000",
    "success": "#34C759",
    "error": "#FF3B30",
    "warning": "#FFB800",
    "info": "#0088EA",
    "orange20": "rgba(235, 113, 0, 0.20)",
    "orange12": "rgba(235, 113, 0, 0.12)",
    "orange08": "rgba(235, 113, 0, 0.08)",
    "text": "rgba(0, 18, 29, 0.90)",
    "textSecondary": "rgba(0, 18, 29, 0.64)",
    "textMuted": "rgba(0, 18, 29, 0.60)",
    "background": "#FFFFFF",
    "surface": "#EDEEEF",
    "cardBackground": "#EDEEEF",
    "primary": "#EB7100",
    "primaryDark": "#D65E00",
    "accent": "#EB7100",
    "accentLight": "#EB7100",
    "tint": "#EB7100",
    "icon": "rgba(0, 18, 29, 0.64)",
    "tabIconDefault": "rgba(0, 18, 29, 0.45)",
    "tabIconSelected": "#EB7100",
    "border": "rgba(0, 18, 29, 0.115)",
    "borderLight": "rgba(0, 18, 29, 0.07)",
    "inputBackground": "rgba(0, 18, 29, 0.058)",
    "inputBorder": "rgba(0, 18, 29, 0.16)",
    "divider": "rgba(0, 18, 29, 0.093)",
    "buttonText": "#FFFFFF",
    "socialBackground": "rgba(0, 18, 29, 0.047)",
    "brandText": "#A85200",
    "accentText": "#A85200",
    "lightBlueBg": "rgba(0, 18, 29, 0.08)",
    "orangeBg": "rgba(235, 113, 0, 0.12)",
    "darkCard": "#FFFFFF",
    "receiptCardBed": "#EDEEEF",
    "brandGradient": [
      "#3E6076",
      "#3E6076"
    ],
    "accentGradient": [
      "#EB7100",
      "#EB7100"
    ],
    "brandMixed": [
      "#EB7100",
      "#EB7100"
    ],
    "chosen": "#00121D",
    "attention": "#EB7100",
    "orangeInk": "#A85200",
    "ambient": "#0088EA",
    "onFill": "rgba(0, 18, 29, 0.75)",
    "tileBackground": "rgba(0, 18, 29, 0.081)",
    "tileIcon": "rgba(0, 18, 29, 0.90)",
    "inkOnFill": "#FFFFFF",
    "destructiveText": "#D70015",
    "warningText": "#8A5A00",
    "successText": "#177034"
  },
  "edgeFadeReach": {
    "neutral": 0.6,
    "important": 0.8,
    "standard": 0.6
  },
  "edgeFadeReachByMode": {
    "dark": {
      "neutral": 0.6,
      "important": 0.8,
      "standard": 0.6
    },
    "light": {
      "neutral": 0.6,
      "important": 0.9,
      "standard": 0.6
    }
  },
  "edgeIntensity": {
    "neutral": 0.6,
    "important": 1,
    "standard": 0.6
  },
  "edgeIntensityByMode": {
    "dark": {
      "neutral": 0.6,
      "important": 1,
      "standard": 0.6
    },
    "light": {
      "neutral": 1,
      "important": 0.75,
      "standard": 1
    }
  },
  "edgeRimProfileByMode": {
    "dark": {
      "curve": {
        "neutral": "linear",
        "important": "linear",
        "standard": "linear"
      },
      "shape": "diagonal"
    },
    "light": {
      "curve": {
        "neutral": "linear",
        "important": "smooth",
        "standard": "linear"
      },
      "shape": "diagonal"
    }
  },
  "glass": {
    "dark": {
      "background": "rgba(255, 255, 255, 0.07)",
      "border": "rgba(255, 255, 255, 0.09)",
      "blurIntensity": 24,
      "blurTint": "dark"
    },
    "light": {
      "background": "rgba(0, 18, 29, 0.09)",
      "border": "rgba(0, 18, 29, 0.16)",
      "blurIntensity": 50,
      "blurTint": "light"
    }
  },
  "glassAccents": {
    "highlight": "rgba(255, 255, 255, 0.28)",
    "shade": "rgba(0, 0, 0, 0.07)"
  },
  "glassAccentsByMode": {
    "dark": {
      "highlight": "rgba(255, 255, 255, 0.28)",
      "shade": "rgba(0, 0, 0, 0.07)"
    },
    "light": {
      "highlight": "rgba(255, 255, 255, 0.90)",
      "shade": "rgba(0, 18, 29, 0.052)"
    }
  },
  "glassEdgeSubtleByMode": {
    "dark": {
      "lit": "rgba(255, 255, 255, 0.132)",
      "far": "rgba(255, 255, 255, 0.132)",
      "faint": "rgba(255, 255, 255, 0.04)",
      "clear": "rgba(255, 255, 255, 0)",
      "wash": "radial-gradient(ellipse farthest-side at 0% 0%, rgba(255, 255, 255, 0.053) 0%, rgba(255, 255, 255, 0) 38%), radial-gradient(ellipse farthest-side at 100% 100%, rgba(255, 255, 255, 0.053) 0%, rgba(255, 255, 255, 0) 38%)",
      "halo": null,
      "outerShadow": null
    },
    "light": {
      "lit": "rgba(0, 18, 29, 0.32)",
      "far": "rgba(0, 18, 29, 0.32)",
      "faint": "rgba(0, 18, 29, 0.18)",
      "clear": "rgba(0, 18, 29, 0)",
      "wash": "radial-gradient(ellipse farthest-side at 0% 0%, rgba(0, 18, 29, 0.128) 0%, rgba(0, 18, 29, 0) 38%), radial-gradient(ellipse farthest-side at 100% 100%, rgba(0, 18, 29, 0.128) 0%, rgba(0, 18, 29, 0) 38%)",
      "halo": null,
      "outerShadow": null
    }
  },
  "glassEdges": {
    "neutral": {
      "lit": "rgba(255, 255, 255, 0.51)",
      "far": "rgba(255, 255, 255, 0.51)",
      "faint": "rgba(255, 255, 255, 0.153)",
      "clear": "rgba(255, 255, 255, 0)",
      "wash": "radial-gradient(ellipse farthest-side at 0% 0%, rgba(255, 255, 255, 0.204) 0%, rgba(255, 255, 255, 0) 38%), radial-gradient(ellipse farthest-side at 100% 100%, rgba(255, 255, 255, 0.204) 0%, rgba(255, 255, 255, 0) 38%)",
      "halo": null,
      "outerShadow": null
    },
    "important": {
      "lit": "rgba(232, 128, 54, 1)",
      "far": "rgba(232, 128, 54, 1)",
      "faint": "rgba(232, 128, 54, 0.3)",
      "clear": "rgba(232, 128, 54, 0)",
      "wash": "radial-gradient(ellipse farthest-side at 0% 0%, rgba(232, 128, 54, 0.4) 0%, rgba(255, 255, 255, 0) 38%), radial-gradient(ellipse farthest-side at 100% 100%, rgba(232, 128, 54, 0.4) 0%, rgba(255, 255, 255, 0) 38%)",
      "halo": "0 0 26px rgba(232, 128, 54, 0.16)",
      "outerShadow": null
    },
    "standard": {
      "lit": "rgba(127, 196, 236, 0.492)",
      "far": "rgba(127, 196, 236, 0.492)",
      "faint": "rgba(127, 196, 236, 0.148)",
      "clear": "rgba(127, 196, 236, 0)",
      "wash": "radial-gradient(ellipse farthest-side at 0% 0%, rgba(127, 196, 236, 0.197) 0%, rgba(255, 255, 255, 0) 38%), radial-gradient(ellipse farthest-side at 100% 100%, rgba(127, 196, 236, 0.197) 0%, rgba(255, 255, 255, 0) 38%)",
      "halo": "0 0 22px rgba(127, 196, 236, 0.036)",
      "outerShadow": null
    }
  },
  "glassEdgesByMode": {
    "dark": {
      "neutral": {
        "lit": "rgba(255, 255, 255, 0.51)",
        "far": "rgba(255, 255, 255, 0.51)",
        "faint": "rgba(255, 255, 255, 0.153)",
        "clear": "rgba(255, 255, 255, 0)",
        "wash": "radial-gradient(ellipse farthest-side at 0% 0%, rgba(255, 255, 255, 0.204) 0%, rgba(255, 255, 255, 0) 38%), radial-gradient(ellipse farthest-side at 100% 100%, rgba(255, 255, 255, 0.204) 0%, rgba(255, 255, 255, 0) 38%)",
        "halo": null,
        "outerShadow": null
      },
      "important": {
        "lit": "rgba(232, 128, 54, 1)",
        "far": "rgba(232, 128, 54, 1)",
        "faint": "rgba(232, 128, 54, 0.3)",
        "clear": "rgba(232, 128, 54, 0)",
        "wash": "radial-gradient(ellipse farthest-side at 0% 0%, rgba(232, 128, 54, 0.4) 0%, rgba(255, 255, 255, 0) 38%), radial-gradient(ellipse farthest-side at 100% 100%, rgba(232, 128, 54, 0.4) 0%, rgba(255, 255, 255, 0) 38%)",
        "halo": "0 0 26px rgba(232, 128, 54, 0.16)",
        "outerShadow": null
      },
      "standard": {
        "lit": "rgba(127, 196, 236, 0.492)",
        "far": "rgba(127, 196, 236, 0.492)",
        "faint": "rgba(127, 196, 236, 0.148)",
        "clear": "rgba(127, 196, 236, 0)",
        "wash": "radial-gradient(ellipse farthest-side at 0% 0%, rgba(127, 196, 236, 0.197) 0%, rgba(255, 255, 255, 0) 38%), radial-gradient(ellipse farthest-side at 100% 100%, rgba(127, 196, 236, 0.197) 0%, rgba(255, 255, 255, 0) 38%)",
        "halo": "0 0 22px rgba(127, 196, 236, 0.036)",
        "outerShadow": null
      }
    },
    "light": {
      "neutral": {
        "lit": "rgba(0, 18, 29, 0.82)",
        "far": "rgba(0, 18, 29, 0.82)",
        "faint": "rgba(0, 18, 29, 0.246)",
        "clear": "rgba(0, 18, 29, 0)",
        "wash": "radial-gradient(ellipse farthest-side at 0% 0%, rgba(0, 18, 29, 0.328) 0%, rgba(0, 18, 29, 0) 38%), radial-gradient(ellipse farthest-side at 100% 100%, rgba(0, 18, 29, 0.328) 0%, rgba(0, 18, 29, 0) 38%)",
        "halo": null,
        "outerShadow": null
      },
      "important": {
        "lit": "rgba(235, 113, 0, 0.75)",
        "far": "rgba(235, 113, 0, 0.75)",
        "faint": "rgba(168, 82, 0, 0.42)",
        "clear": "rgba(235, 113, 0, 0)",
        "wash": "radial-gradient(ellipse farthest-side at 0% 0%, rgba(235, 113, 0, 0.3) 0%, rgba(235, 113, 0, 0) 38%), radial-gradient(ellipse farthest-side at 100% 100%, rgba(235, 113, 0, 0.3) 0%, rgba(235, 113, 0, 0) 38%)",
        "halo": "0 0 26px rgba(235, 113, 0, 0.12)",
        "outerShadow": null
      },
      "standard": {
        "lit": "rgba(0, 18, 29, 0.95)",
        "far": "rgba(0, 18, 29, 0.95)",
        "faint": "rgba(0, 18, 29, 0.285)",
        "clear": "rgba(0, 18, 29, 0)",
        "wash": "radial-gradient(ellipse farthest-side at 0% 0%, rgba(0, 18, 29, 0.38) 0%, rgba(0, 18, 29, 0) 38%), radial-gradient(ellipse farthest-side at 100% 100%, rgba(0, 18, 29, 0.38) 0%, rgba(0, 18, 29, 0) 38%)",
        "halo": "0 0 22px rgba(0, 18, 29, 0.06)",
        "outerShadow": null
      }
    }
  },
  "glassFace": {
    "fill": "transparent",
    "frost": "linear-gradient(128deg, rgba(255, 255, 255, 0.062) 0%, rgba(255, 255, 255, 0.026) 50%, rgba(255, 255, 255, 0.062) 100%)"
  },
  "glassFaceByMode": {
    "dark": {
      "fill": "transparent",
      "frost": "linear-gradient(128deg, rgba(255, 255, 255, 0.062) 0%, rgba(255, 255, 255, 0.026) 50%, rgba(255, 255, 255, 0.062) 100%)"
    },
    "light": {
      "fill": "transparent",
      "frost": "linear-gradient(128deg, rgba(0, 18, 29, 0.0603) 0%, rgba(0, 18, 29, 0.0234) 50%, rgba(0, 18, 29, 0.0603) 100%)"
    }
  },
  "glassFrostAtByMode": {},
  "glassPill": {
    "radius": 9999,
    "paddingVertical": 11,
    "paddingHorizontal": 22,
    "fontSize": 16,
    "fontWeight": "500",
    "shadow": "0 6px 20px rgba(0, 0, 0, 0.3)",
    "accents": {
      "neutral": {
        "full": "rgba(255, 255, 255, 0.95)",
        "mid": "rgba(255, 255, 255, 0.3)",
        "base": "rgba(255, 255, 255, 0.05)",
        "border": "1px solid rgba(255, 255, 255, 0.08)",
        "glow": null,
        "labelColor": "#eef1f4"
      },
      "important": {
        "full": "#e88036",
        "mid": "rgba(232, 128, 54, 0.45)",
        "base": "rgba(232, 128, 54, 0.1)",
        "border": "1px solid rgba(232, 128, 54, 0.2)",
        "glow": "0 0 26px rgba(226, 120, 50, 0.16)",
        "labelColor": null
      },
      "standard": {
        "full": "#78b4eb",
        "mid": "rgba(120, 180, 235, 0.45)",
        "base": "rgba(120, 180, 235, 0.1)",
        "border": "1px solid rgba(120, 180, 235, 0.2)",
        "glow": "0 0 22px rgba(120, 180, 235, 0.14)",
        "labelColor": "#78b4eb"
      }
    }
  },
  "glassPillByMode": {
    "dark": {
      "radius": 9999,
      "paddingVertical": 11,
      "paddingHorizontal": 22,
      "fontSize": 16,
      "fontWeight": "500",
      "shadow": "0 6px 20px rgba(0, 0, 0, 0.3)",
      "accents": {
        "neutral": {
          "full": "rgba(255, 255, 255, 0.95)",
          "mid": "rgba(255, 255, 255, 0.3)",
          "base": "rgba(255, 255, 255, 0.05)",
          "border": "1px solid rgba(255, 255, 255, 0.08)",
          "glow": null,
          "labelColor": "#eef1f4"
        },
        "important": {
          "full": "#e88036",
          "mid": "rgba(232, 128, 54, 0.45)",
          "base": "rgba(232, 128, 54, 0.1)",
          "border": "1px solid rgba(232, 128, 54, 0.2)",
          "glow": "0 0 26px rgba(226, 120, 50, 0.16)",
          "labelColor": null
        },
        "standard": {
          "full": "#78b4eb",
          "mid": "rgba(120, 180, 235, 0.45)",
          "base": "rgba(120, 180, 235, 0.1)",
          "border": "1px solid rgba(120, 180, 235, 0.2)",
          "glow": "0 0 22px rgba(120, 180, 235, 0.14)",
          "labelColor": "#78b4eb"
        }
      }
    },
    "light": {
      "radius": 9999,
      "paddingVertical": 11,
      "paddingHorizontal": 22,
      "fontSize": 16,
      "fontWeight": "500",
      "shadow": "0 6px 20px rgba(0, 18, 29, 0.12)",
      "accents": {
        "neutral": {
          "full": "rgba(0, 18, 29, 0.42)",
          "mid": "rgba(0, 18, 29, 0.16)",
          "base": "rgba(0, 18, 29, 0.05)",
          "border": "1px solid rgba(0, 18, 29, 0.10)",
          "glow": null,
          "labelColor": "#00121D"
        },
        "important": {
          "full": "#EB7100",
          "mid": "rgba(235, 113, 0, 0.45)",
          "base": "rgba(235, 113, 0, 0.1)",
          "border": "1px solid rgba(235, 113, 0, 0.2)",
          "glow": "0 0 26px rgba(235, 113, 0, 0.16)",
          "labelColor": null
        },
        "standard": {
          "full": "#00121D",
          "mid": "rgba(0, 18, 29, 0.45)",
          "base": "rgba(0, 18, 29, 0.1)",
          "border": "1px solid rgba(0, 18, 29, 0.2)",
          "glow": "0 0 22px rgba(0, 18, 29, 0.14)",
          "labelColor": "#00121D"
        }
      }
    }
  },
  "glassPillRing": {
    "reach": 0.38,
    "width": 1,
    "tones": {
      "neutral": {
        "full": "rgba(255, 255, 255, 0.51)",
        "mid": "rgba(255, 255, 255, 0.153)"
      },
      "important": {
        "full": "rgba(232, 128, 54, 1)",
        "mid": "rgba(232, 128, 54, 0.3)"
      },
      "standard": {
        "full": "rgba(127, 196, 236, 0.492)",
        "mid": "rgba(127, 196, 236, 0.148)"
      }
    }
  },
  "glassPillRingByMode": {
    "dark": {
      "reach": 0.38,
      "width": 1,
      "tones": {
        "neutral": {
          "full": "rgba(255, 255, 255, 0.51)",
          "mid": "rgba(255, 255, 255, 0.153)"
        },
        "important": {
          "full": "rgba(232, 128, 54, 1)",
          "mid": "rgba(232, 128, 54, 0.3)"
        },
        "standard": {
          "full": "rgba(127, 196, 236, 0.492)",
          "mid": "rgba(127, 196, 236, 0.148)"
        }
      }
    },
    "light": {
      "reach": 0.38,
      "width": 1,
      "tones": {
        "neutral": {
          "full": "rgba(46, 113, 189, 0.55)",
          "mid": "rgba(46, 113, 189, 0.31)"
        },
        "important": {
          "full": "rgba(235, 113, 0, 0.75)",
          "mid": "rgba(168, 82, 0, 0.42)"
        },
        "standard": {
          "full": "rgba(0, 18, 29, 0.95)",
          "mid": "rgba(0, 18, 29, 0.285)"
        }
      }
    }
  },
  "glassTint05ByMode": {
    "dark": "rgba(255,255,255,0.05)",
    "light": "rgba(0,18,29,0.05)"
  },
  "glassTintAtByMode": {},
  "glassTintByMode": {
    "dark": "rgba(255, 255, 255, 0.062)",
    "light": "rgba(0, 18, 29, 0.0603)"
  },
  "iconSize": {
    "sm": 18,
    "md": 24,
    "lg": 32
  },
  "orangeTints": {
    "orange20": "rgba(235, 113, 0, 0.20)",
    "orange12": "rgba(235, 113, 0, 0.12)",
    "orange08": "rgba(235, 113, 0, 0.08)"
  },
  "radii": {
    "sm": 8,
    "md": 12,
    "lg": 18,
    "xl": 24,
    "pill": 28,
    "full": 9999
  },
  "recentBarAccentByMode": {
    "dark": {
      "fill": "rgba(214,222,230,0.14)",
      "line": "rgba(214,222,230,0.55)"
    },
    "light": {
      "fill": "rgba(0,18,29,0.10)",
      "line": "rgba(0,18,29,0.45)"
    }
  },
  "shadowsDark": {
    "sm": {
      "shadowOffset": {
        "width": 0,
        "height": 1
      },
      "shadowRadius": 3,
      "elevation": 2,
      "shadowColor": "#000",
      "shadowOpacity": 0.4
    },
    "md": {
      "shadowOffset": {
        "width": 0,
        "height": 4
      },
      "shadowRadius": 8,
      "elevation": 4,
      "shadowColor": "#000",
      "shadowOpacity": 0.5
    },
    "lg": {
      "shadowOffset": {
        "width": 0,
        "height": 8
      },
      "shadowRadius": 16,
      "elevation": 8,
      "shadowColor": "#000",
      "shadowOpacity": 0.6
    },
    "glass": {
      "shadowOffset": {
        "width": 0,
        "height": 12
      },
      "shadowRadius": 20,
      "elevation": 10,
      "shadowColor": "#000",
      "shadowOpacity": 0.14
    },
    "fab": {
      "shadowOffset": {
        "width": 0,
        "height": 8
      },
      "shadowRadius": 12,
      "elevation": 8,
      "shadowColor": "#EB7100",
      "shadowOpacity": 0.45
    }
  },
  "shadowsLight": {
    "sm": {
      "shadowOffset": {
        "width": 0,
        "height": 1
      },
      "shadowRadius": 3,
      "elevation": 0,
      "shadowColor": "#00121D",
      "shadowOpacity": 0
    },
    "md": {
      "shadowOffset": {
        "width": 0,
        "height": 4
      },
      "shadowRadius": 8,
      "elevation": 0,
      "shadowColor": "#00121D",
      "shadowOpacity": 0
    },
    "lg": {
      "shadowOffset": {
        "width": 0,
        "height": 8
      },
      "shadowRadius": 16,
      "elevation": 0,
      "shadowColor": "#00121D",
      "shadowOpacity": 0
    },
    "glass": {
      "shadowOffset": {
        "width": 0,
        "height": 12
      },
      "shadowRadius": 20,
      "elevation": 0,
      "shadowColor": "#00121D",
      "shadowOpacity": 0
    },
    "fab": {
      "shadowOffset": {
        "width": 0,
        "height": 8
      },
      "shadowRadius": 12,
      "elevation": 8,
      "shadowColor": "#EB7100",
      "shadowOpacity": 0.45
    }
  },
  "spacing": {
    "xs": 4,
    "sm": 8,
    "md": 16,
    "lg": 24,
    "xl": 32,
    "xxl": 48
  },
  "typography": {
    "h1": {
      "fontFamily": "Barlow-Bold",
      "fontSize": 34,
      "letterSpacing": -0.68
    },
    "h2": {
      "fontFamily": "Barlow-Bold",
      "fontSize": 28,
      "letterSpacing": -0.56
    },
    "h3": {
      "fontFamily": "Barlow-Bold",
      "fontSize": 20,
      "letterSpacing": -0.4
    },
    "body": {
      "fontFamily": "Barlow-Regular",
      "fontSize": 15,
      "lineHeight": 22
    },
    "caption": {
      "fontFamily": "Barlow-Regular",
      "fontSize": 13,
      "lineHeight": 18
    },
    "small": {
      "fontFamily": "Barlow-Regular",
      "fontSize": 11,
      "lineHeight": 16
    },
    "label": {
      "fontFamily": "Barlow-Medium",
      "fontSize": 14
    },
    "button": {
      "fontFamily": "Barlow-SemiBold",
      "fontSize": 17,
      "letterSpacing": -0.68
    },
    "eyebrow": {
      "fontFamily": "IBMPlexMono-Medium",
      "fontSize": 11,
      "letterSpacing": 0.88,
      "textTransform": "uppercase"
    },
    "stat": {
      "fontFamily": "IBMPlexMono-SemiBold",
      "fontSize": 30,
      "letterSpacing": -0.6
    },
    "statSecondary": {
      "fontFamily": "IBMPlexMono-SemiBold",
      "fontSize": 24,
      "letterSpacing": -0.48
    },
    "statTile": {
      "fontFamily": "IBMPlexMono-SemiBold",
      "fontSize": 22,
      "letterSpacing": -0.44
    }
  }
} as const;

/** PapeXV2 `theme/motion/tokens.ts` (durations, springs; easing functions omitted). */
export const motion = {
  "chartReveal": {
    "durationMs": 1600,
    "easingBezier": [
      0.16,
      1,
      0.3,
      1
    ]
  },
  "disclosure": {
    "openSpring": {
      "friction": 20,
      "tension": 240
    },
    "openMs": 260,
    "closeMs": 180
  },
  "entrance": {
    "rnSpring": {
      "friction": 10,
      "tension": 90
    },
    "spring": {
      "stiffness": 411.20000000000005,
      "damping": 31,
      "mass": 1
    },
    "riseDistance": 8,
    "staggerMs": 50,
    "staggerMaxSteps": 6,
    "planeFlightMs": 1500
  },
  "fade": {
    "inMs": 260,
    "outMs": 180,
    "easingBezier": [
      0.25,
      0,
      0.2,
      1
    ],
    "splashMs": 800,
    "systemModalDismissMs": 400
  },
  "indicator": {
    "slideMs": 260,
    "slideEasingBezier": [
      0.3333333333333333,
      1,
      0.6666666666666666,
      1
    ]
  },
  "loop": {
    "shimmerMs": 600,
    "shimmerFrom": 0.3,
    "shimmerTo": 0.7,
    "pulseMs": 900,
    "pulseScale": 1.05,
    "breatheMs": 1400,
    "breatheRise": -10,
    "breatheScale": 1.04,
    "spinMs": 1800,
    "spinBezier": [
      0.4,
      0,
      0.6,
      1
    ],
    "spinSlowMs": 2400,
    "halfTurnHold": {
      "input": [
        0,
        0.4,
        0.5,
        0.9,
        1
      ],
      "outputDeg": [
        0,
        0,
        180,
        180,
        360
      ]
    }
  },
  "menu": {
    "openSpring": {
      "friction": 10,
      "tension": 90
    },
    "openScale": 0.5,
    "closeMs": 140
  },
  "progress": {
    "stepMs": 600
  },
  "swipe": {
    "returnSpring": {
      "damping": 20,
      "stiffness": 220,
      "mass": 0.55
    },
    "flyMs": 220
  },
  "touchResponse": {
    "growMs": 130,
    "releaseMs": 190,
    "easingBezier": [
      0.3333333333333333,
      1,
      0.6666666666666666,
      1
    ],
    "pressedScale": 0.97,
    "pressedOpacity": 0.85,
    "activeOpacity": 0.8
  }
} as const;

/** PapeXV2 `components/ui/pills/pillTokens.ts`. */
export const pills = {
  "CAP_DROP_EM": {
    "barlow": 0.05,
    "plexMono": 0.026
  },
  "PILL_DISABLED_OPACITY": 0.38,
  "PILL_GLOW_DEFAULT": "standard",
  "PILL_MAX_FONT_SCALE": 1.3,
  "PILL_ROW_SLOP": 7,
  "PILL_TONES": [
    "neutral",
    "attention",
    "shared"
  ],
  "SELECTION_RADIUS": 14,
  "SHARED_GLOW_U_LIGHT": true,
  "WIDE_FACE_INSET": 0.67,
  "countGeometry": {
    "height": 18,
    "minWidth": 18,
    "radius": 8.4,
    "padX": 5,
    "max": 99
  },
  "countTones": {
    "attention": {
      "fill": "#EB7100",
      "ink": "#00121D",
      "sheen": "linear-gradient(180deg, rgba(255, 255, 255, 0.22), rgba(255, 255, 255, 0) 60%)"
    },
    "neutral": {
      "fill": "rgba(255, 255, 255, 0.14)",
      "ink": "#FFFFFF",
      "sheen": "linear-gradient(180deg, rgba(255, 255, 255, 0.22), rgba(255, 255, 255, 0) 60%)"
    }
  },
  "pillButtonGeometry": {
    "md": {
      "height": 30,
      "radius": 14,
      "padLead": 10,
      "padTrail": 12,
      "padText": 12,
      "gap": 5,
      "iconSize": 16,
      "hitSlop": {
        "top": 7,
        "bottom": 7,
        "left": 4,
        "right": 4
      }
    },
    "sm": {
      "height": 30,
      "radius": 14,
      "padLead": 10,
      "padTrail": 13,
      "padText": 13,
      "gap": 5,
      "iconSize": 16,
      "hitSlop": {
        "top": 7,
        "bottom": 7,
        "left": 4,
        "right": 4
      }
    }
  },
  "pillDrag": {
    "activateX": 8,
    "failY": 10,
    "holdMs": 250,
    "offRow": 44
  },
  "pillGeometry": {
    "height": 30,
    "radius": 15,
    "iconSize": 16,
    "gap": 5,
    "padLead": 10,
    "padTrail": 12,
    "padText": 12,
    "trailingIconSize": 14,
    "trailingGap": 4,
    "hitSlop": {
      "top": 7,
      "bottom": 7,
      "left": 4,
      "right": 4
    }
  },
  "pillGleamBand": {
    "bandFullBelow": 90,
    "radialFullFrom": 110,
    "span": 0.85,
    "ramp": 0.35
  },
  "pillGleamWidth": {
    "shortWidth": 44,
    "longWidth": 110,
    "minFactor": 0.35
  },
  "pillInk": {
    "rest": "rgba(255, 255, 255, 0.64)",
    "selected": "#FFFFFF"
  },
  "pillMoreGeometry": {
    "width": 46
  },
  "pillMotion": {
    "litMs": 220,
    "litBezier": [
      0.25,
      0,
      0.2,
      1
    ],
    "pressedScale": 0.97
  },
  "pillPalette": {
    "rest": {
      "fill": "rgba(255, 255, 255, 0.047)",
      "shadow": "inset 0 1px 0 rgba(255, 255, 255, 0.1), inset 0 0 0 1px rgba(255, 255, 255, 0.04), 0 4px 12px rgba(0, 0, 0, 0.22)",
      "drop": "0 4px 12px rgba(0, 0, 0, 0.22)",
      "ink": "rgba(255, 255, 255, 0.72)",
      "iconInk": "rgba(255, 255, 255, 0.72)",
      "menuInk": "rgba(255, 255, 255, 0.84)"
    },
    "selected": {
      "fill": "rgba(255, 255, 255, 0.157)",
      "tint": "linear-gradient(0deg, rgba(255, 255, 255, 0.12), rgba(255, 255, 255, 0.078) 18%, rgba(255, 255, 255, 0.036) 36%, rgba(255, 255, 255, 0.012) 48%, rgba(255, 255, 255, 0) 58%)",
      "gradient": "linear-gradient(180deg, rgba(255, 255, 255, 0.235), rgba(255, 255, 255, 0.078))",
      "drop": "0 6px 14px rgba(0, 0, 0, 0.3)",
      "rim": "inset 0 -20px 8px -18px rgba(0, 0, 0, 0.16)",
      "gleam": {
        "top": 0,
        "height": 5,
        "inset": 6,
        "adaptive": true,
        "image": "radial-gradient(ellipse 50% 100% at 50% 0%, rgba(255, 255, 255, 0.25), rgba(255, 255, 255, 0.1) 45%, rgba(255, 255, 255, 0))",
        "band": {
          "left": "radial-gradient(ellipse 100% 100% at 100% 0%, rgba(255, 255, 255, 0.25), rgba(255, 255, 255, 0.1) 45%, rgba(255, 255, 255, 0))",
          "mid": "linear-gradient(180deg, rgba(255, 255, 255, 0.25), rgba(255, 255, 255, 0.1) 45%, rgba(255, 255, 255, 0))",
          "right": "radial-gradient(ellipse 100% 100% at 0% 0%, rgba(255, 255, 255, 0.25), rgba(255, 255, 255, 0.1) 45%, rgba(255, 255, 255, 0))"
        }
      },
      "ink": "#FFFFFF",
      "iconInk": "#FFFFFF"
    },
    "iconCrossFade": false
  },
  "pillPanelBlur": {
    "intensity": 50,
    "tint": "dark"
  },
  "pillPressWash": "rgba(255, 255, 255, 0.08)",
  "pillPressWashByMode": {
    "dark": "rgba(255, 255, 255, 0.08)",
    "light": "rgba(0, 18, 29, 0.1)"
  },
  "pillQuietFace": {
    "drop": "0 6px 14px rgba(0, 0, 0, 0.3)",
    "sheen": "linear-gradient(180deg, rgba(255, 255, 255, 0.235), rgba(255, 255, 255, 0.078))",
    "shade": "inset 0 -20px 8px -18px rgba(0, 0, 0, 0.16)",
    "gleam": {
      "top": 0,
      "height": 5,
      "inset": 6,
      "adaptive": true,
      "image": "radial-gradient(ellipse 50% 100% at 50% 0%, rgba(255, 255, 255, 0.25), rgba(255, 255, 255, 0.1) 45%, rgba(255, 255, 255, 0))",
      "band": {
        "left": "radial-gradient(ellipse 100% 100% at 100% 0%, rgba(255, 255, 255, 0.25), rgba(255, 255, 255, 0.1) 45%, rgba(255, 255, 255, 0))",
        "mid": "linear-gradient(180deg, rgba(255, 255, 255, 0.25), rgba(255, 255, 255, 0.1) 45%, rgba(255, 255, 255, 0))",
        "right": "radial-gradient(ellipse 100% 100% at 0% 0%, rgba(255, 255, 255, 0.25), rgba(255, 255, 255, 0.1) 45%, rgba(255, 255, 255, 0))"
      }
    }
  },
  "pillRowGeometry": {
    "spacing": 8,
    "inset": 16,
    "padTop": 12,
    "padBottom": 28
  },
  "pillToneLayers": {
    "neutral": {
      "tint": "linear-gradient(0deg, rgba(255, 255, 255, 0.12), rgba(255, 255, 255, 0.078) 18%, rgba(255, 255, 255, 0.036) 36%, rgba(255, 255, 255, 0.012) 48%, rgba(255, 255, 255, 0) 58%)"
    },
    "shared": {
      "tint": "linear-gradient(0deg, rgba(0, 136, 234, 0.2), rgba(0, 136, 234, 0.13) 18%, rgba(0, 136, 234, 0.06) 36%, rgba(0, 136, 234, 0.02) 48%, rgba(0, 136, 234, 0) 58%)",
      "line": "inset 0 -1px 0 rgba(0, 136, 234, 0.36)"
    },
    "attention": {
      "tint": "linear-gradient(0deg, rgba(235, 113, 0, 0.18), rgba(235, 113, 0, 0.117) 18%, rgba(235, 113, 0, 0.054) 36%, rgba(235, 113, 0, 0.018) 48%, rgba(235, 113, 0, 0) 58%)",
      "line": "inset 0 -1px 0 rgba(235, 113, 0, 0.34)"
    }
  },
  "pillTones": {
    "neutral": {
      "rest": {
        "fill": "rgba(255, 255, 255, 0.047)",
        "shadow": "inset 0 1px 0 rgba(255, 255, 255, 0.1), inset 0 0 0 1px rgba(255, 255, 255, 0.04), 0 4px 12px rgba(0, 0, 0, 0.22)",
        "drop": "0 4px 12px rgba(0, 0, 0, 0.22)",
        "ink": "rgba(255, 255, 255, 0.72)",
        "iconInk": "rgba(255, 255, 255, 0.72)",
        "menuInk": "rgba(255, 255, 255, 0.84)"
      },
      "selected": {
        "fill": "rgba(255, 255, 255, 0.157)",
        "tint": "linear-gradient(0deg, rgba(255, 255, 255, 0.12), rgba(255, 255, 255, 0.078) 18%, rgba(255, 255, 255, 0.036) 36%, rgba(255, 255, 255, 0.012) 48%, rgba(255, 255, 255, 0) 58%)",
        "gradient": "linear-gradient(180deg, rgba(255, 255, 255, 0.235), rgba(255, 255, 255, 0.078))",
        "drop": "0 6px 14px rgba(0, 0, 0, 0.3)",
        "rim": "inset 0 -20px 8px -18px rgba(0, 0, 0, 0.16)",
        "gleam": {
          "top": 0,
          "height": 5,
          "inset": 6,
          "adaptive": true,
          "image": "radial-gradient(ellipse 50% 100% at 50% 0%, rgba(255, 255, 255, 0.25), rgba(255, 255, 255, 0.1) 45%, rgba(255, 255, 255, 0))",
          "band": {
            "left": "radial-gradient(ellipse 100% 100% at 100% 0%, rgba(255, 255, 255, 0.25), rgba(255, 255, 255, 0.1) 45%, rgba(255, 255, 255, 0))",
            "mid": "linear-gradient(180deg, rgba(255, 255, 255, 0.25), rgba(255, 255, 255, 0.1) 45%, rgba(255, 255, 255, 0))",
            "right": "radial-gradient(ellipse 100% 100% at 0% 0%, rgba(255, 255, 255, 0.25), rgba(255, 255, 255, 0.1) 45%, rgba(255, 255, 255, 0))"
          }
        },
        "ink": "#FFFFFF",
        "iconInk": "#FFFFFF"
      },
      "iconCrossFade": false
    },
    "attention": {
      "rest": {
        "fill": "rgba(255, 255, 255, 0.047)",
        "shadow": "inset 0 1px 0 rgba(255, 255, 255, 0.1), inset 0 0 0 1px rgba(255, 255, 255, 0.04), 0 4px 12px rgba(0, 0, 0, 0.22)",
        "drop": "0 4px 12px rgba(0, 0, 0, 0.22)",
        "ink": "rgba(255, 255, 255, 0.72)",
        "iconInk": "rgba(255, 255, 255, 0.72)",
        "menuInk": "rgba(255, 255, 255, 0.84)"
      },
      "selected": {
        "fill": "rgba(255, 255, 255, 0.157)",
        "tint": "linear-gradient(0deg, rgba(235, 113, 0, 0.18), rgba(235, 113, 0, 0.117) 18%, rgba(235, 113, 0, 0.054) 36%, rgba(235, 113, 0, 0.018) 48%, rgba(235, 113, 0, 0) 58%)",
        "gradient": "linear-gradient(180deg, rgba(255, 255, 255, 0.235), rgba(255, 255, 255, 0.078))",
        "drop": "0 6px 14px rgba(0, 0, 0, 0.3)",
        "rim": "inset 0 -1px 0 rgba(235, 113, 0, 0.34), inset 0 -20px 8px -18px rgba(0, 0, 0, 0.16)",
        "gleam": {
          "top": 0,
          "height": 5,
          "inset": 6,
          "adaptive": true,
          "image": "radial-gradient(ellipse 50% 100% at 50% 0%, rgba(255, 255, 255, 0.25), rgba(255, 255, 255, 0.1) 45%, rgba(255, 255, 255, 0))",
          "band": {
            "left": "radial-gradient(ellipse 100% 100% at 100% 0%, rgba(255, 255, 255, 0.25), rgba(255, 255, 255, 0.1) 45%, rgba(255, 255, 255, 0))",
            "mid": "linear-gradient(180deg, rgba(255, 255, 255, 0.25), rgba(255, 255, 255, 0.1) 45%, rgba(255, 255, 255, 0))",
            "right": "radial-gradient(ellipse 100% 100% at 0% 0%, rgba(255, 255, 255, 0.25), rgba(255, 255, 255, 0.1) 45%, rgba(255, 255, 255, 0))"
          }
        },
        "ink": "#FFFFFF",
        "iconInk": "#FFFFFF"
      },
      "iconCrossFade": false
    },
    "shared": {
      "rest": {
        "fill": "rgba(255, 255, 255, 0.047)",
        "shadow": "inset 0 1px 0 rgba(255, 255, 255, 0.1), inset 0 0 0 1px rgba(255, 255, 255, 0.04), 0 4px 12px rgba(0, 0, 0, 0.22)",
        "drop": "0 4px 12px rgba(0, 0, 0, 0.22)",
        "ink": "rgba(255, 255, 255, 0.72)",
        "iconInk": "rgba(255, 255, 255, 0.72)",
        "menuInk": "rgba(255, 255, 255, 0.84)"
      },
      "selected": {
        "fill": "rgba(255, 255, 255, 0.157)",
        "tint": "linear-gradient(0deg, rgba(0, 136, 234, 0.2), rgba(0, 136, 234, 0.13) 18%, rgba(0, 136, 234, 0.06) 36%, rgba(0, 136, 234, 0.02) 48%, rgba(0, 136, 234, 0) 58%)",
        "gradient": "linear-gradient(180deg, rgba(255, 255, 255, 0.235), rgba(255, 255, 255, 0.078))",
        "drop": "0 6px 14px rgba(0, 0, 0, 0.3)",
        "rim": "inset 0 -1px 0 rgba(0, 136, 234, 0.36), inset 0 -20px 8px -18px rgba(0, 0, 0, 0.16)",
        "gleam": {
          "top": 0,
          "height": 5,
          "inset": 6,
          "adaptive": true,
          "image": "radial-gradient(ellipse 50% 100% at 50% 0%, rgba(255, 255, 255, 0.25), rgba(255, 255, 255, 0.1) 45%, rgba(255, 255, 255, 0))",
          "band": {
            "left": "radial-gradient(ellipse 100% 100% at 100% 0%, rgba(255, 255, 255, 0.25), rgba(255, 255, 255, 0.1) 45%, rgba(255, 255, 255, 0))",
            "mid": "linear-gradient(180deg, rgba(255, 255, 255, 0.25), rgba(255, 255, 255, 0.1) 45%, rgba(255, 255, 255, 0))",
            "right": "radial-gradient(ellipse 100% 100% at 0% 0%, rgba(255, 255, 255, 0.25), rgba(255, 255, 255, 0.1) 45%, rgba(255, 255, 255, 0))"
          }
        },
        "ink": "#FFFFFF",
        "iconInk": "#FFFFFF"
      },
      "iconCrossFade": false
    }
  },
  "pillType": {
    "label": {
      "fontFamily": "Barlow-Medium",
      "fontSize": 13,
      "lineHeight": 16,
      "letterSpacing": -0.1,
      "capDropEm": 0.05
    },
    "button": {
      "fontFamily": "Barlow-SemiBold",
      "fontSize": 13,
      "lineHeight": 16,
      "letterSpacing": -0.1,
      "capDropEm": 0.05
    },
    "buttonSm": {
      "fontFamily": "Barlow-SemiBold",
      "fontSize": 13,
      "lineHeight": 16,
      "letterSpacing": -0.1,
      "capDropEm": 0.05
    },
    "tag": {
      "fontFamily": "Barlow-Medium",
      "fontSize": 12,
      "lineHeight": 15,
      "capDropEm": 0.05
    },
    "count": {
      "fontFamily": "IBMPlexMono-SemiBold",
      "fontSize": 11,
      "lineHeight": 14,
      "tabular": true,
      "capDropEm": 0.026
    }
  },
  "tabTrackGeometry": {
    "height": 36,
    "equalHeight": 30,
    "equalMinFontScale": 1,
    "tabBarHeight": 48,
    "pad": 3,
    "equalPad": 1,
    "inset": 16,
    "padX": 10,
    "padXCompact": 8,
    "padXTight": 6,
    "iconSize": 16,
    "tabBarIconSize": 18,
    "gap": 5,
    "stackGap": 2,
    "trailingIconSize": 14,
    "trailingGap": 4,
    "minCell": 44,
    "touchTarget": 44,
    "gridRowHeight": 40,
    "gridRows": 2,
    "gridMaxSingleRow": 4,
    "minFontScale": 0.75,
    "labelSlack": 1,
    "dividerWidth": 0.3333333333333333,
    "dividerHeight": 14
  },
  "tabTrackInk": {
    "rest": "rgba(255, 255, 255, 0.72)",
    "menuRest": "rgba(255, 255, 255, 0.84)",
    "selected": "#FFFFFF",
    "divider": "rgba(255, 255, 255, 0.16)"
  },
  "tabTrackInkLight": {
    "rest": "rgba(0, 18, 29, 0.72)",
    "menuRest": "rgba(0, 18, 29, 0.84)",
    "selected": "#00121D",
    "divider": "rgba(0, 136, 234, 0.28)"
  },
  "tabTrackMotion": {
    "moveMs": 260,
    "moveBezier": [
      0.3333333333333333,
      1,
      0.6666666666666666,
      1
    ],
    "wordToIconDelayMs": 1200,
    "litMs": 220,
    "litBezier": [
      0.25,
      0,
      0.2,
      1
    ]
  },
  "tabTrackType": {
    "label": {
      "fontFamily": "Barlow-Medium",
      "fontSize": 13,
      "lineHeight": 16,
      "letterSpacing": -0.1,
      "capDropEm": 0.05
    },
    "tabBar": {
      "fontFamily": "Barlow-Medium",
      "fontSize": 11,
      "lineHeight": 14,
      "letterSpacing": 0,
      "capDropEm": 0.05
    },
    "menu": {
      "fontFamily": "Barlow-SemiBold",
      "fontSize": 13,
      "lineHeight": 16,
      "letterSpacing": -0.1,
      "capDropEm": 0.05
    }
  },
  "tagGeometry": {
    "height": 24,
    "radius": 11.2,
    "padX": 10,
    "gap": 4,
    "iconSize": 14
  },
  "tagIconInk": {
    "neutral": "#FFFFFF",
    "attention": "rgb(243, 170, 102)",
    "shared": "rgb(128, 196, 245)"
  },
  "tagOnFillFace": {
    "fill": "rgba(0, 18, 29, 0.75)"
  },
  "tagToneLayers": {
    "neutral": {
      "tint": "linear-gradient(0deg, rgba(255, 255, 255, 0.12), rgba(255, 255, 255, 0.078) 18%, rgba(255, 255, 255, 0.036) 36%, rgba(255, 255, 255, 0.012) 48%, rgba(255, 255, 255, 0) 58%)"
    },
    "attention": {
      "tint": "linear-gradient(0deg, rgba(235, 113, 0, 0.3), rgba(235, 113, 0, 0.21) 25%, rgba(235, 113, 0, 0.12) 45%, rgba(235, 113, 0, 0.045) 62%, rgba(235, 113, 0, 0) 80%)",
      "line": "inset 0 -1px 0 rgba(235, 113, 0, 0.34)"
    },
    "shared": {
      "tint": "linear-gradient(0deg, rgba(0, 136, 234, 0.32), rgba(0, 136, 234, 0.224) 25%, rgba(0, 136, 234, 0.128) 45%, rgba(0, 136, 234, 0.048) 62%, rgba(0, 136, 234, 0) 80%)",
      "line": "inset 0 -1px 0 rgba(0, 136, 234, 0.36)"
    }
  }
} as const;

/** PapeXV2 `components/ui/tabBarMetrics.ts` (evaluated as iOS). */
export const tabBarMetrics = {
  "TAB_BAR_BOTTOM_OFFSET": 0,
  "TAB_BAR_CONTENT_GAP": 12,
  "TAB_BAR_HEIGHT": 49
} as const;

/** Papex_AppClip `Sources/AppClip/PapeXTheme.swift`. */
export const clip = {
  "color": {
    "navy": "#00121D",
    "orange": "#EB7100",
    "blue": "#0088EA",
    "standardOutline": "#7FC4EC",
    "green": "#34C759",
    "textPrimary": "rgba(255, 255, 255, 0.9)",
    "textSecondary": "rgba(255, 255, 255, 0.64)",
    "textMuted": "rgba(255, 255, 255, 0.45)",
    "cardSurface": "rgba(255, 255, 255, 0.06)",
    "cardBorder": "rgba(255, 255, 255, 0.09)",
    "hairline": "rgba(255, 255, 255, 0.18)"
  },
  "font": {
    "family": "Barlow",
    "faceByWeight": {
      "bold": "Barlow-Bold",
      "heavy": "Barlow-Bold",
      "black": "Barlow-Bold",
      "semibold": "Barlow-SemiBold",
      "medium": "Barlow-Medium",
      "regular": "Barlow-Regular"
    }
  },
  "spacing": {
    "xs": 8,
    "sm": 16,
    "md": 24,
    "lg": 40
  },
  "radius": {
    "card": 28,
    "button": 12,
    "pill": 9999
  },
  "glassCard": {
    "rimStops": [
      {
        "opacity": 0.85,
        "location": 0
      },
      {
        "opacity": 0,
        "location": 0.35
      },
      {
        "opacity": 0,
        "location": 0.65
      },
      {
        "opacity": 0.55,
        "location": 1
      }
    ],
    "rimWidth": 1,
    "fill": "rgba(255, 255, 255, 0.06)"
  },
  "background": {
    "base": "#00121D",
    "glows": [
      {
        "color": "rgba(235, 113, 0, 0.16)",
        "x": 0.12,
        "y": 0.07,
        "startRadius": 0,
        "endRadius": 380
      },
      {
        "color": "rgba(235, 113, 0, 0.13)",
        "x": 0.9,
        "y": 0.96,
        "startRadius": 0,
        "endRadius": 420
      }
    ]
  }
} as const;

/** Function-valued exports sampled by calling them: glassFrostAt(1), glassTintAt(1), pillTokensFor(mode). */
export const samples = {
  "glassFrostAt1": {
    "dark": "linear-gradient(128deg, rgba(255, 255, 255, 0.062) 0%, rgba(255, 255, 255, 0.026) 50%, rgba(255, 255, 255, 0.062) 100%)",
    "light": "linear-gradient(128deg, rgba(0, 18, 29, 0.067) 0%, rgba(0, 18, 29, 0.026) 50%, rgba(0, 18, 29, 0.067) 100%)"
  },
  "glassTintAt1": {
    "dark": "rgba(255, 255, 255, 0.062)",
    "light": "rgba(0, 18, 29, 0.067)"
  },
  "pillTokensFor": {
    "dark": {
      "pillInk": {
        "rest": "rgba(255, 255, 255, 0.64)",
        "selected": "#FFFFFF"
      },
      "pillQuietFace": {
        "drop": "0 6px 14px rgba(0, 0, 0, 0.3)",
        "sheen": "linear-gradient(180deg, rgba(255, 255, 255, 0.235), rgba(255, 255, 255, 0.078))",
        "shade": "inset 0 -20px 8px -18px rgba(0, 0, 0, 0.16)",
        "gleam": {
          "top": 0,
          "height": 5,
          "inset": 6,
          "adaptive": true,
          "image": "radial-gradient(ellipse 50% 100% at 50% 0%, rgba(255, 255, 255, 0.25), rgba(255, 255, 255, 0.1) 45%, rgba(255, 255, 255, 0))",
          "band": {
            "left": "radial-gradient(ellipse 100% 100% at 100% 0%, rgba(255, 255, 255, 0.25), rgba(255, 255, 255, 0.1) 45%, rgba(255, 255, 255, 0))",
            "mid": "linear-gradient(180deg, rgba(255, 255, 255, 0.25), rgba(255, 255, 255, 0.1) 45%, rgba(255, 255, 255, 0))",
            "right": "radial-gradient(ellipse 100% 100% at 0% 0%, rgba(255, 255, 255, 0.25), rgba(255, 255, 255, 0.1) 45%, rgba(255, 255, 255, 0))"
          }
        }
      },
      "pillToneLayers": {
        "neutral": {
          "tint": "linear-gradient(0deg, rgba(255, 255, 255, 0.12), rgba(255, 255, 255, 0.078) 18%, rgba(255, 255, 255, 0.036) 36%, rgba(255, 255, 255, 0.012) 48%, rgba(255, 255, 255, 0) 58%)"
        },
        "shared": {
          "tint": "linear-gradient(0deg, rgba(0, 136, 234, 0.2), rgba(0, 136, 234, 0.13) 18%, rgba(0, 136, 234, 0.06) 36%, rgba(0, 136, 234, 0.02) 48%, rgba(0, 136, 234, 0) 58%)",
          "line": "inset 0 -1px 0 rgba(0, 136, 234, 0.36)"
        },
        "attention": {
          "tint": "linear-gradient(0deg, rgba(235, 113, 0, 0.18), rgba(235, 113, 0, 0.117) 18%, rgba(235, 113, 0, 0.054) 36%, rgba(235, 113, 0, 0.018) 48%, rgba(235, 113, 0, 0) 58%)",
          "line": "inset 0 -1px 0 rgba(235, 113, 0, 0.34)"
        }
      },
      "tagToneLayers": {
        "neutral": {
          "tint": "linear-gradient(0deg, rgba(255, 255, 255, 0.12), rgba(255, 255, 255, 0.078) 18%, rgba(255, 255, 255, 0.036) 36%, rgba(255, 255, 255, 0.012) 48%, rgba(255, 255, 255, 0) 58%)"
        },
        "attention": {
          "tint": "linear-gradient(0deg, rgba(235, 113, 0, 0.3), rgba(235, 113, 0, 0.21) 25%, rgba(235, 113, 0, 0.12) 45%, rgba(235, 113, 0, 0.045) 62%, rgba(235, 113, 0, 0) 80%)",
          "line": "inset 0 -1px 0 rgba(235, 113, 0, 0.34)"
        },
        "shared": {
          "tint": "linear-gradient(0deg, rgba(0, 136, 234, 0.32), rgba(0, 136, 234, 0.224) 25%, rgba(0, 136, 234, 0.128) 45%, rgba(0, 136, 234, 0.048) 62%, rgba(0, 136, 234, 0) 80%)",
          "line": "inset 0 -1px 0 rgba(0, 136, 234, 0.36)"
        }
      },
      "tagIconInk": {
        "neutral": "#FFFFFF",
        "attention": "rgb(243, 170, 102)",
        "shared": "rgb(128, 196, 245)"
      },
      "tagOnFillFace": {
        "fill": "rgba(0, 18, 29, 0.75)"
      },
      "pillTones": {
        "neutral": {
          "rest": {
            "fill": "rgba(255, 255, 255, 0.047)",
            "shadow": "inset 0 1px 0 rgba(255, 255, 255, 0.1), inset 0 0 0 1px rgba(255, 255, 255, 0.04), 0 4px 12px rgba(0, 0, 0, 0.22)",
            "drop": "0 4px 12px rgba(0, 0, 0, 0.22)",
            "ink": "rgba(255, 255, 255, 0.72)",
            "iconInk": "rgba(255, 255, 255, 0.72)",
            "menuInk": "rgba(255, 255, 255, 0.84)"
          },
          "selected": {
            "fill": "rgba(255, 255, 255, 0.157)",
            "tint": "linear-gradient(0deg, rgba(255, 255, 255, 0.12), rgba(255, 255, 255, 0.078) 18%, rgba(255, 255, 255, 0.036) 36%, rgba(255, 255, 255, 0.012) 48%, rgba(255, 255, 255, 0) 58%)",
            "gradient": "linear-gradient(180deg, rgba(255, 255, 255, 0.235), rgba(255, 255, 255, 0.078))",
            "drop": "0 6px 14px rgba(0, 0, 0, 0.3)",
            "rim": "inset 0 -20px 8px -18px rgba(0, 0, 0, 0.16)",
            "gleam": {
              "top": 0,
              "height": 5,
              "inset": 6,
              "adaptive": true,
              "image": "radial-gradient(ellipse 50% 100% at 50% 0%, rgba(255, 255, 255, 0.25), rgba(255, 255, 255, 0.1) 45%, rgba(255, 255, 255, 0))",
              "band": {
                "left": "radial-gradient(ellipse 100% 100% at 100% 0%, rgba(255, 255, 255, 0.25), rgba(255, 255, 255, 0.1) 45%, rgba(255, 255, 255, 0))",
                "mid": "linear-gradient(180deg, rgba(255, 255, 255, 0.25), rgba(255, 255, 255, 0.1) 45%, rgba(255, 255, 255, 0))",
                "right": "radial-gradient(ellipse 100% 100% at 0% 0%, rgba(255, 255, 255, 0.25), rgba(255, 255, 255, 0.1) 45%, rgba(255, 255, 255, 0))"
              }
            },
            "ink": "#FFFFFF",
            "iconInk": "#FFFFFF"
          },
          "iconCrossFade": false
        },
        "attention": {
          "rest": {
            "fill": "rgba(255, 255, 255, 0.047)",
            "shadow": "inset 0 1px 0 rgba(255, 255, 255, 0.1), inset 0 0 0 1px rgba(255, 255, 255, 0.04), 0 4px 12px rgba(0, 0, 0, 0.22)",
            "drop": "0 4px 12px rgba(0, 0, 0, 0.22)",
            "ink": "rgba(255, 255, 255, 0.72)",
            "iconInk": "rgba(255, 255, 255, 0.72)",
            "menuInk": "rgba(255, 255, 255, 0.84)"
          },
          "selected": {
            "fill": "rgba(255, 255, 255, 0.157)",
            "tint": "linear-gradient(0deg, rgba(235, 113, 0, 0.18), rgba(235, 113, 0, 0.117) 18%, rgba(235, 113, 0, 0.054) 36%, rgba(235, 113, 0, 0.018) 48%, rgba(235, 113, 0, 0) 58%)",
            "gradient": "linear-gradient(180deg, rgba(255, 255, 255, 0.235), rgba(255, 255, 255, 0.078))",
            "drop": "0 6px 14px rgba(0, 0, 0, 0.3)",
            "rim": "inset 0 -1px 0 rgba(235, 113, 0, 0.34), inset 0 -20px 8px -18px rgba(0, 0, 0, 0.16)",
            "gleam": {
              "top": 0,
              "height": 5,
              "inset": 6,
              "adaptive": true,
              "image": "radial-gradient(ellipse 50% 100% at 50% 0%, rgba(255, 255, 255, 0.25), rgba(255, 255, 255, 0.1) 45%, rgba(255, 255, 255, 0))",
              "band": {
                "left": "radial-gradient(ellipse 100% 100% at 100% 0%, rgba(255, 255, 255, 0.25), rgba(255, 255, 255, 0.1) 45%, rgba(255, 255, 255, 0))",
                "mid": "linear-gradient(180deg, rgba(255, 255, 255, 0.25), rgba(255, 255, 255, 0.1) 45%, rgba(255, 255, 255, 0))",
                "right": "radial-gradient(ellipse 100% 100% at 0% 0%, rgba(255, 255, 255, 0.25), rgba(255, 255, 255, 0.1) 45%, rgba(255, 255, 255, 0))"
              }
            },
            "ink": "#FFFFFF",
            "iconInk": "#FFFFFF"
          },
          "iconCrossFade": false
        },
        "shared": {
          "rest": {
            "fill": "rgba(255, 255, 255, 0.047)",
            "shadow": "inset 0 1px 0 rgba(255, 255, 255, 0.1), inset 0 0 0 1px rgba(255, 255, 255, 0.04), 0 4px 12px rgba(0, 0, 0, 0.22)",
            "drop": "0 4px 12px rgba(0, 0, 0, 0.22)",
            "ink": "rgba(255, 255, 255, 0.72)",
            "iconInk": "rgba(255, 255, 255, 0.72)",
            "menuInk": "rgba(255, 255, 255, 0.84)"
          },
          "selected": {
            "fill": "rgba(255, 255, 255, 0.157)",
            "tint": "linear-gradient(0deg, rgba(0, 136, 234, 0.2), rgba(0, 136, 234, 0.13) 18%, rgba(0, 136, 234, 0.06) 36%, rgba(0, 136, 234, 0.02) 48%, rgba(0, 136, 234, 0) 58%)",
            "gradient": "linear-gradient(180deg, rgba(255, 255, 255, 0.235), rgba(255, 255, 255, 0.078))",
            "drop": "0 6px 14px rgba(0, 0, 0, 0.3)",
            "rim": "inset 0 -1px 0 rgba(0, 136, 234, 0.36), inset 0 -20px 8px -18px rgba(0, 0, 0, 0.16)",
            "gleam": {
              "top": 0,
              "height": 5,
              "inset": 6,
              "adaptive": true,
              "image": "radial-gradient(ellipse 50% 100% at 50% 0%, rgba(255, 255, 255, 0.25), rgba(255, 255, 255, 0.1) 45%, rgba(255, 255, 255, 0))",
              "band": {
                "left": "radial-gradient(ellipse 100% 100% at 100% 0%, rgba(255, 255, 255, 0.25), rgba(255, 255, 255, 0.1) 45%, rgba(255, 255, 255, 0))",
                "mid": "linear-gradient(180deg, rgba(255, 255, 255, 0.25), rgba(255, 255, 255, 0.1) 45%, rgba(255, 255, 255, 0))",
                "right": "radial-gradient(ellipse 100% 100% at 0% 0%, rgba(255, 255, 255, 0.25), rgba(255, 255, 255, 0.1) 45%, rgba(255, 255, 255, 0))"
              }
            },
            "ink": "#FFFFFF",
            "iconInk": "#FFFFFF"
          },
          "iconCrossFade": false
        }
      },
      "pillPalette": {
        "rest": {
          "fill": "rgba(255, 255, 255, 0.047)",
          "shadow": "inset 0 1px 0 rgba(255, 255, 255, 0.1), inset 0 0 0 1px rgba(255, 255, 255, 0.04), 0 4px 12px rgba(0, 0, 0, 0.22)",
          "drop": "0 4px 12px rgba(0, 0, 0, 0.22)",
          "ink": "rgba(255, 255, 255, 0.72)",
          "iconInk": "rgba(255, 255, 255, 0.72)",
          "menuInk": "rgba(255, 255, 255, 0.84)"
        },
        "selected": {
          "fill": "rgba(255, 255, 255, 0.157)",
          "tint": "linear-gradient(0deg, rgba(255, 255, 255, 0.12), rgba(255, 255, 255, 0.078) 18%, rgba(255, 255, 255, 0.036) 36%, rgba(255, 255, 255, 0.012) 48%, rgba(255, 255, 255, 0) 58%)",
          "gradient": "linear-gradient(180deg, rgba(255, 255, 255, 0.235), rgba(255, 255, 255, 0.078))",
          "drop": "0 6px 14px rgba(0, 0, 0, 0.3)",
          "rim": "inset 0 -20px 8px -18px rgba(0, 0, 0, 0.16)",
          "gleam": {
            "top": 0,
            "height": 5,
            "inset": 6,
            "adaptive": true,
            "image": "radial-gradient(ellipse 50% 100% at 50% 0%, rgba(255, 255, 255, 0.25), rgba(255, 255, 255, 0.1) 45%, rgba(255, 255, 255, 0))",
            "band": {
              "left": "radial-gradient(ellipse 100% 100% at 100% 0%, rgba(255, 255, 255, 0.25), rgba(255, 255, 255, 0.1) 45%, rgba(255, 255, 255, 0))",
              "mid": "linear-gradient(180deg, rgba(255, 255, 255, 0.25), rgba(255, 255, 255, 0.1) 45%, rgba(255, 255, 255, 0))",
              "right": "radial-gradient(ellipse 100% 100% at 0% 0%, rgba(255, 255, 255, 0.25), rgba(255, 255, 255, 0.1) 45%, rgba(255, 255, 255, 0))"
            }
          },
          "ink": "#FFFFFF",
          "iconInk": "#FFFFFF"
        },
        "iconCrossFade": false
      },
      "pillPressWash": "rgba(255, 255, 255, 0.08)",
      "pillPanelBlur": {
        "intensity": 50,
        "tint": "dark"
      },
      "countTones": {
        "attention": {
          "fill": "#EB7100",
          "ink": "#00121D",
          "sheen": "linear-gradient(180deg, rgba(255, 255, 255, 0.22), rgba(255, 255, 255, 0) 60%)"
        },
        "neutral": {
          "fill": "rgba(255, 255, 255, 0.14)",
          "ink": "#FFFFFF",
          "sheen": "linear-gradient(180deg, rgba(255, 255, 255, 0.22), rgba(255, 255, 255, 0) 60%)"
        }
      },
      "tabTrackInk": {
        "rest": "rgba(255, 255, 255, 0.72)",
        "menuRest": "rgba(255, 255, 255, 0.84)",
        "selected": "#FFFFFF",
        "divider": "rgba(255, 255, 255, 0.16)"
      }
    },
    "light": {
      "pillInk": {
        "rest": "rgba(0, 18, 29, 0.72)",
        "selected": "#00121D"
      },
      "pillQuietFace": {
        "drop": "0 0 0 0 rgba(0, 18, 29, 0)",
        "sheen": "linear-gradient(180deg, rgba(46, 115, 189, 0.18), rgba(46, 115, 189, 0.06)), linear-gradient(180deg, rgba(255, 255, 255, 0.5), rgba(255, 255, 255, 0.16))",
        "shade": "inset 0 0 0 1px rgba(0, 18, 29, 0.18), inset 0 -20px 8px -18px rgba(0, 18, 29, 0.06)",
        "gleam": {
          "top": 0,
          "height": 5,
          "inset": 6,
          "adaptive": true,
          "image": "radial-gradient(ellipse 50% 100% at 50% 0%, rgba(255, 255, 255, 0.14), rgba(255, 255, 255, 0.056) 45%, rgba(255, 255, 255, 0))",
          "band": {
            "left": "radial-gradient(ellipse 100% 100% at 100% 0%, rgba(255, 255, 255, 0.14), rgba(255, 255, 255, 0.056) 45%, rgba(255, 255, 255, 0))",
            "mid": "linear-gradient(180deg, rgba(255, 255, 255, 0.14), rgba(255, 255, 255, 0.056) 45%, rgba(255, 255, 255, 0))",
            "right": "radial-gradient(ellipse 100% 100% at 0% 0%, rgba(255, 255, 255, 0.14), rgba(255, 255, 255, 0.056) 45%, rgba(255, 255, 255, 0))"
          }
        }
      },
      "pillToneLayers": {
        "neutral": {
          "tint": "linear-gradient(0deg, rgba(255, 255, 255, 1), rgba(255, 255, 255, 0.65) 18%, rgba(255, 255, 255, 0.3) 36%, rgba(255, 255, 255, 0.1) 48%, rgba(255, 255, 255, 0) 58%)"
        },
        "shared": {
          "tint": "linear-gradient(0deg, rgba(0, 136, 234, 0.9), rgba(0, 136, 234, 0.585) 18%, rgba(0, 136, 234, 0.27) 36%, rgba(0, 136, 234, 0.09) 48%, rgba(0, 136, 234, 0) 58%)",
          "line": "inset 0 -1px 0 rgba(0, 136, 234, 0.45)"
        },
        "attention": {
          "tint": "linear-gradient(0deg, rgba(235, 113, 0, 0.675), rgba(235, 113, 0, 0.518) 13%, rgba(235, 113, 0, 0.34) 26%, rgba(235, 113, 0, 0.173) 39%, rgba(235, 113, 0, 0.049) 52%, rgba(235, 113, 0, 0) 65%)",
          "line": "inset 0 -1px 0 rgba(235, 113, 0, 0.3)"
        }
      },
      "tagToneLayers": {
        "neutral": {
          "tint": "linear-gradient(0deg, rgba(255, 255, 255, 1), rgba(255, 255, 255, 0.65) 18%, rgba(255, 255, 255, 0.3) 36%, rgba(255, 255, 255, 0.1) 48%, rgba(255, 255, 255, 0) 58%)"
        },
        "attention": {
          "tint": "linear-gradient(0deg, rgba(235, 113, 0, 0.315), rgba(235, 113, 0, 0.242) 18%, rgba(235, 113, 0, 0.159) 36%, rgba(235, 113, 0, 0.081) 54%, rgba(235, 113, 0, 0.023) 72%, rgba(235, 113, 0, 0) 90%)",
          "line": "inset 0 -1px 0 rgba(235, 113, 0, 0.3)"
        },
        "shared": {
          "tint": "linear-gradient(0deg, rgba(0, 136, 234, 0.42), rgba(0, 136, 234, 0.294) 25%, rgba(0, 136, 234, 0.168) 45%, rgba(0, 136, 234, 0.063) 62%, rgba(0, 136, 234, 0) 80%)",
          "line": "inset 0 -1px 0 rgba(0, 136, 234, 0.45)"
        }
      },
      "tagIconInk": {
        "neutral": "#00121D",
        "attention": "#A85200",
        "shared": "#006BB8"
      },
      "tagOnFillFace": {
        "fill": "rgba(0, 18, 29, 0.75)"
      },
      "pillTones": {
        "neutral": {
          "rest": {
            "fill": "rgba(0, 18, 29, 0.075)",
            "shadow": "inset 0 1px 0 rgba(255, 255, 255, 0.3), inset 0 0 0 1px rgba(0, 18, 29, 0.18)",
            "drop": null,
            "ink": "rgba(0, 18, 29, 0.72)",
            "iconInk": "rgba(0, 18, 29, 0.72)",
            "menuInk": "rgba(0, 18, 29, 0.84)"
          },
          "selected": {
            "fill": "rgba(0, 136, 234, 0.1)",
            "tint": "linear-gradient(0deg, rgba(255, 255, 255, 1), rgba(255, 255, 255, 0.65) 18%, rgba(255, 255, 255, 0.3) 36%, rgba(255, 255, 255, 0.1) 48%, rgba(255, 255, 255, 0) 58%)",
            "gradient": "linear-gradient(180deg, rgba(46, 115, 189, 0.18), rgba(46, 115, 189, 0.06)), linear-gradient(180deg, rgba(255, 255, 255, 0.5), rgba(255, 255, 255, 0.16))",
            "drop": "0 0 0 0 rgba(0, 18, 29, 0)",
            "rim": "inset 0 0 0 1px rgba(0, 18, 29, 0.18), inset 0 -20px 8px -18px rgba(0, 18, 29, 0.06)",
            "gleam": {
              "top": 0,
              "height": 5,
              "inset": 6,
              "adaptive": true,
              "image": "radial-gradient(ellipse 50% 100% at 50% 0%, rgba(255, 255, 255, 0.14), rgba(255, 255, 255, 0.056) 45%, rgba(255, 255, 255, 0))",
              "band": {
                "left": "radial-gradient(ellipse 100% 100% at 100% 0%, rgba(255, 255, 255, 0.14), rgba(255, 255, 255, 0.056) 45%, rgba(255, 255, 255, 0))",
                "mid": "linear-gradient(180deg, rgba(255, 255, 255, 0.14), rgba(255, 255, 255, 0.056) 45%, rgba(255, 255, 255, 0))",
                "right": "radial-gradient(ellipse 100% 100% at 0% 0%, rgba(255, 255, 255, 0.14), rgba(255, 255, 255, 0.056) 45%, rgba(255, 255, 255, 0))"
              }
            },
            "ink": "#00121D",
            "iconInk": "#00121D"
          },
          "iconCrossFade": false
        },
        "attention": {
          "rest": {
            "fill": "rgba(0, 18, 29, 0.075)",
            "shadow": "inset 0 1px 0 rgba(255, 255, 255, 0.3), inset 0 0 0 1px rgba(0, 18, 29, 0.18)",
            "drop": null,
            "ink": "rgba(0, 18, 29, 0.72)",
            "iconInk": "rgba(0, 18, 29, 0.72)",
            "menuInk": "rgba(0, 18, 29, 0.84)"
          },
          "selected": {
            "fill": "rgba(0, 136, 234, 0.1)",
            "tint": "linear-gradient(0deg, rgba(235, 113, 0, 0.675), rgba(235, 113, 0, 0.518) 13%, rgba(235, 113, 0, 0.34) 26%, rgba(235, 113, 0, 0.173) 39%, rgba(235, 113, 0, 0.049) 52%, rgba(235, 113, 0, 0) 65%)",
            "gradient": "linear-gradient(180deg, rgba(46, 115, 189, 0.18), rgba(46, 115, 189, 0.06)), linear-gradient(180deg, rgba(255, 255, 255, 0.5), rgba(255, 255, 255, 0.16))",
            "drop": "0 0 0 0 rgba(0, 18, 29, 0)",
            "rim": "inset 0 -1px 0 rgba(235, 113, 0, 0.3), inset 0 0 0 1px rgba(0, 18, 29, 0.18), inset 0 -20px 8px -18px rgba(0, 18, 29, 0.06)",
            "gleam": {
              "top": 0,
              "height": 5,
              "inset": 6,
              "adaptive": true,
              "image": "radial-gradient(ellipse 50% 100% at 50% 0%, rgba(255, 255, 255, 0.14), rgba(255, 255, 255, 0.056) 45%, rgba(255, 255, 255, 0))",
              "band": {
                "left": "radial-gradient(ellipse 100% 100% at 100% 0%, rgba(255, 255, 255, 0.14), rgba(255, 255, 255, 0.056) 45%, rgba(255, 255, 255, 0))",
                "mid": "linear-gradient(180deg, rgba(255, 255, 255, 0.14), rgba(255, 255, 255, 0.056) 45%, rgba(255, 255, 255, 0))",
                "right": "radial-gradient(ellipse 100% 100% at 0% 0%, rgba(255, 255, 255, 0.14), rgba(255, 255, 255, 0.056) 45%, rgba(255, 255, 255, 0))"
              }
            },
            "ink": "#00121D",
            "iconInk": "#00121D"
          },
          "iconCrossFade": false
        },
        "shared": {
          "rest": {
            "fill": "rgba(0, 18, 29, 0.075)",
            "shadow": "inset 0 1px 0 rgba(255, 255, 255, 0.3), inset 0 0 0 1px rgba(0, 18, 29, 0.18)",
            "drop": null,
            "ink": "rgba(0, 18, 29, 0.72)",
            "iconInk": "rgba(0, 18, 29, 0.72)",
            "menuInk": "rgba(0, 18, 29, 0.84)"
          },
          "selected": {
            "fill": "rgba(0, 136, 234, 0.1)",
            "tint": "linear-gradient(0deg, rgba(0, 136, 234, 0.9), rgba(0, 136, 234, 0.585) 18%, rgba(0, 136, 234, 0.27) 36%, rgba(0, 136, 234, 0.09) 48%, rgba(0, 136, 234, 0) 58%)",
            "gradient": "linear-gradient(180deg, rgba(46, 115, 189, 0.18), rgba(46, 115, 189, 0.06)), linear-gradient(180deg, rgba(255, 255, 255, 0.5), rgba(255, 255, 255, 0.16))",
            "drop": "0 0 0 0 rgba(0, 18, 29, 0)",
            "rim": "inset 0 -1px 0 rgba(0, 136, 234, 0.45), inset 0 0 0 1px rgba(0, 18, 29, 0.18), inset 0 -20px 8px -18px rgba(0, 18, 29, 0.06)",
            "gleam": {
              "top": 0,
              "height": 5,
              "inset": 6,
              "adaptive": true,
              "image": "radial-gradient(ellipse 50% 100% at 50% 0%, rgba(255, 255, 255, 0.14), rgba(255, 255, 255, 0.056) 45%, rgba(255, 255, 255, 0))",
              "band": {
                "left": "radial-gradient(ellipse 100% 100% at 100% 0%, rgba(255, 255, 255, 0.14), rgba(255, 255, 255, 0.056) 45%, rgba(255, 255, 255, 0))",
                "mid": "linear-gradient(180deg, rgba(255, 255, 255, 0.14), rgba(255, 255, 255, 0.056) 45%, rgba(255, 255, 255, 0))",
                "right": "radial-gradient(ellipse 100% 100% at 0% 0%, rgba(255, 255, 255, 0.14), rgba(255, 255, 255, 0.056) 45%, rgba(255, 255, 255, 0))"
              }
            },
            "ink": "#00121D",
            "iconInk": "#00121D"
          },
          "iconCrossFade": false
        }
      },
      "pillPalette": {
        "rest": {
          "fill": "rgba(0, 18, 29, 0.075)",
          "shadow": "inset 0 1px 0 rgba(255, 255, 255, 0.3), inset 0 0 0 1px rgba(0, 18, 29, 0.18)",
          "drop": null,
          "ink": "rgba(0, 18, 29, 0.72)",
          "iconInk": "rgba(0, 18, 29, 0.72)",
          "menuInk": "rgba(0, 18, 29, 0.84)"
        },
        "selected": {
          "fill": "rgba(0, 136, 234, 0.1)",
          "tint": "linear-gradient(0deg, rgba(255, 255, 255, 1), rgba(255, 255, 255, 0.65) 18%, rgba(255, 255, 255, 0.3) 36%, rgba(255, 255, 255, 0.1) 48%, rgba(255, 255, 255, 0) 58%)",
          "gradient": "linear-gradient(180deg, rgba(46, 115, 189, 0.18), rgba(46, 115, 189, 0.06)), linear-gradient(180deg, rgba(255, 255, 255, 0.5), rgba(255, 255, 255, 0.16))",
          "drop": "0 0 0 0 rgba(0, 18, 29, 0)",
          "rim": "inset 0 0 0 1px rgba(0, 18, 29, 0.18), inset 0 -20px 8px -18px rgba(0, 18, 29, 0.06)",
          "gleam": {
            "top": 0,
            "height": 5,
            "inset": 6,
            "adaptive": true,
            "image": "radial-gradient(ellipse 50% 100% at 50% 0%, rgba(255, 255, 255, 0.14), rgba(255, 255, 255, 0.056) 45%, rgba(255, 255, 255, 0))",
            "band": {
              "left": "radial-gradient(ellipse 100% 100% at 100% 0%, rgba(255, 255, 255, 0.14), rgba(255, 255, 255, 0.056) 45%, rgba(255, 255, 255, 0))",
              "mid": "linear-gradient(180deg, rgba(255, 255, 255, 0.14), rgba(255, 255, 255, 0.056) 45%, rgba(255, 255, 255, 0))",
              "right": "radial-gradient(ellipse 100% 100% at 0% 0%, rgba(255, 255, 255, 0.14), rgba(255, 255, 255, 0.056) 45%, rgba(255, 255, 255, 0))"
            }
          },
          "ink": "#00121D",
          "iconInk": "#00121D"
        },
        "iconCrossFade": false
      },
      "pillPressWash": "rgba(0, 18, 29, 0.1)",
      "pillPanelBlur": {
        "intensity": 50,
        "tint": "light"
      },
      "countTones": {
        "attention": {
          "fill": "#EB7100",
          "ink": "#00121D",
          "sheen": "linear-gradient(180deg, rgba(255, 255, 255, 0.22), rgba(255, 255, 255, 0) 60%)"
        },
        "neutral": {
          "fill": "rgba(0, 18, 29, 0.1)",
          "ink": "#00121D",
          "sheen": "linear-gradient(180deg, rgba(255, 255, 255, 0.5), rgba(255, 255, 255, 0) 60%)"
        }
      },
      "tabTrackInk": {
        "rest": "rgba(0, 18, 29, 0.72)",
        "menuRest": "rgba(0, 18, 29, 0.84)",
        "selected": "#00121D",
        "divider": "rgba(0, 136, 234, 0.28)"
      }
    }
  }
} as const;

/** Function-valued exports that could not be copied as data. */
export const OMITTED_FUNCTIONS = [
  "motion.chartReveal.easing",
  "motion.disclosure.closeEasing",
  "motion.disclosure.durationFor",
  "motion.disclosure.easingFor",
  "motion.disclosure.openEasing",
  "motion.fade.easing",
  "motion.loop.easing",
  "motion.loop.spinEasing",
  "motion.menu.closeEasing",
  "motion.toReanimatedSpring",
  "motion.touchResponse.easing",
  "pills.opticalLift",
  "pills.pillTokensFor",
  "pills.pillToneLayerTable",
  "pills.selectionRadius",
  "tabBarMetrics.getTabBarBottomContentInset",
  "tabBarMetrics.getTabBarBottomOffset",
  "tabBarMetrics.getTabBarScrollBottomSpacer",
  "theme.glassFrostAt",
  "theme.glassFrostAtByMode.dark",
  "theme.glassFrostAtByMode.light",
  "theme.glassFrostAtLight",
  "theme.glassTintAt",
  "theme.glassTintAtByMode.dark",
  "theme.glassTintAtByMode.light",
  "theme.glassTintAtLight"
] as const;
